var snapVersion = '7.0.1'

var cacheName = 'snap-ai-pwa',
    filesToCache = [
        'snap/snap.html',

        // program
        'snap/src/morphic.js',
        'snap/src/symbols.js',
        'snap/src/widgets.js',
        'snap/src/blocks.js',
        'snap/src/threads.js',
        'snap/src/objects.js',
        'snap/src/scenes.js',
        'snap/src/gui.js',
        'snap/src/paint.js',
        'snap/src/lists.js',
        'snap/src/byob.js',
        'snap/src/tables.js',
        'snap/src/sketch.js',
        'snap/src/video.js',
        'snap/src/maps.js',
        'snap/src/extensions.js',
        'snap/src/xml.js',
        'snap/src/store.js',
        'snap/src/locale.js',
        'snap/src/cloud.js',
        'snap/src/api.js',
        'snap/src/sha512.js',
        'snap/src/FileSaver.min.js',

        // translations
        'snap/locale/lang-ar.js',
        'snap/locale/lang-bg.js',
        'snap/locale/lang-bn.js',
        'snap/locale/lang-ca.js',
        'snap/locale/lang-ca_VA.js',
        'snap/locale/lang-cs.js',
        'snap/locale/lang-de.js',
        'snap/locale/lang-dk.js',
        'snap/locale/lang-el.js',
        'snap/locale/lang-eo.js',
        'snap/locale/lang-es.js',
        'snap/locale/lang-et.js',
        'snap/locale/lang-eu.js',
        'snap/locale/lang-fi.js',
        'snap/locale/lang-fr.js',
        'snap/locale/lang-gl.js',
        'snap/locale/lang-he.js',
        'snap/locale/lang-hi.js',
        'snap/locale/lang-hr.js',
        'snap/locale/lang-hu.js',
        'snap/locale/lang-ia.js',
        'snap/locale/lang-id.js',
        'snap/locale/lang-it.js',
        'snap/locale/lang-ja_HIRA.js',
        'snap/locale/lang-ja.js',
        'snap/locale/lang-kn.js',
        'snap/locale/lang-ko.js',
        'snap/locale/lang-ml.js',
        'snap/locale/lang-nl.js',
        'snap/locale/lang-no.js',
        'snap/locale/lang-pl.js',
        'snap/locale/lang-pt_BR.js',
        'snap/locale/lang-pt.js',
        'snap/locale/lang-ro.js',
        'snap/locale/lang-ru.js',
        'snap/locale/lang-si.js',
        'snap/locale/lang-sk.js',
        'snap/locale/lang-sv.js',
        'snap/locale/lang-ta.js',
        'snap/locale/lang-te.js',
        'snap/locale/lang-tr.js',
        'snap/locale/lang-ua.js',
        'snap/locale/lang-zh_CN.js',
        'snap/locale/lang-zh_TW.js',

        //libraries
        'snap/libraries/LIBRARIES',

        'snap/libraries/animation_module.xml',
        'snap/libraries/apl.xml',
        'snap/libraries/audioComp_module.xml',
        'snap/libraries/bar-charts.xml',
        'snap/libraries/biginteger.js',
        'snap/libraries/bignumbers.xml',
        'snap/libraries/bignums.js',
        'snap/libraries/bbtSnapExtension.js',
        'snap/libraries/cases.xml',
        'snap/libraries/colors.xml',
        'snap/libraries/Eisenbergification.xml',
        'snap/libraries/frequency_distribution_module.xml',
        'snap/libraries/httpBlocks.xml',
        'snap/libraries/HummingbirdBlocks.xml',
        'snap/libraries/iteration-composition.xml',
        'snap/libraries/leap-library.xml',
        'snap/libraries/list-utilities.xml',
        'snap/libraries/localstorage_module.xml',
        'snap/libraries/make-variables.xml',
        'snap/libraries/maps_module.xml',
        'snap/libraries/parallel_module.xml',
        'snap/libraries/pixel_module.xml',
        'snap/libraries/schemeNumber.js',
        'snap/libraries/serial_module.xml',
        'snap/libraries/signada.js',
        'snap/libraries/signada.xml',
        'snap/libraries/speech_module.xml',
        'snap/libraries/stream-tools.xml',
        'snap/libraries/strings.xml',
        'snap/libraries/textCostumes_module.xml',
        'snap/libraries/try-catch.xml',
        'snap/libraries/variadic-reporters.xml',
        'snap/libraries/word-sentence.xml',

        //costumes
        'snap/Costumes/COSTUMES',

        'snap/Costumes/abby-a.svg',
        'snap/Costumes/abby-b.svg',
        'snap/Costumes/abby-c.svg',
        'snap/Costumes/abby-d.svg',
        'snap/Costumes/airplane2.png',
        'snap/Costumes/alonzo.png',
        'snap/Costumes/Alonzo3D.png',
        'snap/Costumes/alonzo.svg',
        'snap/Costumes/amon.gif',
        'snap/Costumes/anina_pop_down.png',
        'snap/Costumes/anina_pop_front.png',
        'snap/Costumes/anina_pop_L_arm.png',
        'snap/Costumes/anina_pop_left.png',
        'snap/Costumes/anina_pop_R_arm.png',
        'snap/Costumes/anina_pop_right.png',
        'snap/Costumes/anina_pop_stand.png',
        'snap/Costumes/anina_R_cross.png',
        'snap/Costumes/anina_stance.png',
        'snap/Costumes/anina_top_freeze.png',
        'snap/Costumes/anina_top_L_step.png',
        'snap/Costumes/anina_top_R_step.png',
        'snap/Costumes/anina_top_stand.png',
        'snap/Costumes/anna01.png',
        'snap/Costumes/anna02.png',
        'snap/Costumes/anna03.png',
        'snap/Costumes/anna04.png',
        'snap/Costumes/anna05.png',
        'snap/Costumes/anna06.png',
        'snap/Costumes/anna07b.png',
        'snap/Costumes/anna07c.png',
        'snap/Costumes/anna07.png',
        'snap/Costumes/anna08.png',
        'snap/Costumes/anna09.png',
        'snap/Costumes/anna10.png',
        'snap/Costumes/anna11.png',
        'snap/Costumes/anna12.png',
        'snap/Costumes/anna-a.png',
        'snap/Costumes/anna-b.png',
        'snap/Costumes/apple.svg',
        'snap/Costumes/arrow1-a.svg',
        'snap/Costumes/arrow1-b.svg',
        'snap/Costumes/arrow1-c.svg',
        'snap/Costumes/arrow1-d.svg',
        'snap/Costumes/avery-a.svg',
        'snap/Costumes/avery-b.svg',
        'snap/Costumes/avery_walking-a.svg',
        'snap/Costumes/avery_walking-b.svg',
        'snap/Costumes/avery_walking-c.svg',
        'snap/Costumes/avery_walking-d.svg',
        'snap/Costumes/AZ_pop_down.png',
        'snap/Costumes/AZ_pop_front.png',
        'snap/Costumes/AZ_pop_L_arm.png',
        'snap/Costumes/AZ_pop_left.png',
        'snap/Costumes/AZ_pop_R_arm.png',
        'snap/Costumes/AZ_pop_right.png',
        'snap/Costumes/AZ_pop_stand.png',
        'snap/Costumes/AZ_stance.png',
        'snap/Costumes/AZ_top_freeze.png',
        'snap/Costumes/AZ_top_L_step.png',
        'snap/Costumes/AZ_top_R_cross.png',
        'snap/Costumes/AZ_top_R_step.png',
        'snap/Costumes/AZ_top_stand.png',
        'snap/Costumes/ball-a.svg',
        'snap/Costumes/ball-b.svg',
        'snap/Costumes/ball-c.svg',
        'snap/Costumes/ball-d.svg',
        'snap/Costumes/ballerina-a.svg',
        'snap/Costumes/ballerina-b.svg',
        'snap/Costumes/ballerina-c.svg',
        'snap/Costumes/ballerina-d.svg',
        'snap/Costumes/ball-e.svg',
        'snap/Costumes/balloon1-a.svg',
        'snap/Costumes/balloon1-b.svg',
        'snap/Costumes/balloon1-c.svg',
        'snap/Costumes/ball-soccer.svg',
        'snap/Costumes/bananas.svg',
        'snap/Costumes/baseball.svg',
        'snap/Costumes/basketball.svg',
        'snap/Costumes/bass.svg',
        'snap/Costumes/bat1-a_.svg',
        'snap/Costumes/bat1-b_.svg',
        'snap/Costumes/bat2-a_.svg',
        'snap/Costumes/bat2-b_.svg',
        'snap/Costumes/beachball.svg',
        'snap/Costumes/bear2-a.svg',
        'snap/Costumes/bear2-b.svg',
        'snap/Costumes/beetle.svg',
        'snap/Costumes/bell1.svg',
        'snap/Costumes/bells-a.svg',
        'snap/Costumes/bells-b.svg',
        'snap/Costumes/bowl-a.svg',
        'snap/Costumes/bowtie-a.svg',
        'snap/Costumes/bowtie-b.svg',
        'snap/Costumes/boy1-standing.gif',
        'snap/Costumes/boy1-walking.gif',
        'snap/Costumes/boy2.gif',
        'snap/Costumes/boy3.gif',
        'snap/Costumes/building-a.svg',
        'snap/Costumes/building-b.svg',
        'snap/Costumes/building-c.svg',
        'snap/Costumes/building-d.svg',
        'snap/Costumes/building-e.svg',
        'snap/Costumes/building-f.svg',
        'snap/Costumes/building-g.svg',
        'snap/Costumes/building-h.svg',
        'snap/Costumes/building-i.svg',
        'snap/Costumes/building-j.svg',
        'snap/Costumes/bus.png',
        'snap/Costumes/butterfly1-a.svg',
        'snap/Costumes/butterfly1-b_.svg',
        'snap/Costumes/butterfly2_.svg',
        'snap/Costumes/butterfly3_.svg',
        'snap/Costumes/button1.svg',
        'snap/Costumes/button2-a.svg',
        'snap/Costumes/button2-b.svg',
        'snap/Costumes/button3-a.svg',
        'snap/Costumes/button3-b.svg',
        'snap/Costumes/button4-a.svg',
        'snap/Costumes/button4-b.svg',
        'snap/Costumes/button5-a.svg',
        'snap/Costumes/button5-b.svg',
        'snap/Costumes/cake-a.svg',
        'snap/Costumes/cake-b.svg',
        'snap/Costumes/calvrett_jumping.png',
        'snap/Costumes/calvrett_thinking.png',
        'snap/Costumes/candle1-a.svg',
        'snap/Costumes/candle1-b.svg',
        'snap/Costumes/candles1.svg',
        'snap/Costumes/candles2.svg',
        'snap/Costumes/car-bug.png',
        'snap/Costumes/cassy-a.png',
        'snap/Costumes/cassy-b.png',
        'snap/Costumes/cassy-c.png',
        'snap/Costumes/cassy_dance-a.png',
        'snap/Costumes/cassy_dance-b.png',
        'snap/Costumes/cassy_dance-c.png',
        'snap/Costumes/cassy_dance-d.png',
        'snap/Costumes/cassy-d.png',
        'snap/Costumes/cat2.gif',
        'snap/Costumes/cat2.svg',
        'snap/Costumes/cat3.png',
        'snap/Costumes/cat4.png',
        'snap/Costumes/cat5.gif',
        'snap/Costumes/catherine-a.png',
        'snap/Costumes/catherine-b.png',
        'snap/Costumes/catherine-c.png',
        'snap/Costumes/catherine-d.png',
        'snap/Costumes/champ99-a.png',
        'snap/Costumes/champ99-b.png',
        'snap/Costumes/champ99-c.png',
        'snap/Costumes/champ99-d.png',
        'snap/Costumes/champ99-e.png',
        'snap/Costumes/champ99-f.png',
        'snap/Costumes/champ99-g.png',
        'snap/Costumes/cheesy-puffs.png',
        'snap/Costumes/cloud-a.svg',
        'snap/Costumes/cloud-b.svg',
        'snap/Costumes/cloud-c.svg',
        'snap/Costumes/cloud-d.svg',
        'snap/Costumes/cloud.svg',
        'snap/Costumes/cm_pop_L_arm.png',
        'snap/Costumes/cm_pop_R_arm.png',
        'snap/Costumes/cm_top_L_cross.png',
        'snap/Costumes/cm_top_L_leg.png',
        'snap/Costumes/cm_top_R_cross.png',
        'snap/Costumes/cm_top_ready.png',
        'snap/Costumes/cm_top_R_leg.png',
        'snap/Costumes/cm_top_stand.png',
        'snap/Costumes/convertible1.png',
        'snap/Costumes/convertible2.png',
        'snap/Costumes/convertible3.svg',
        'snap/Costumes/cowbell.svg',
        'snap/Costumes/crab-a.svg',
        'snap/Costumes/crab-b.svg',
        'snap/Costumes/creature1-a.svg',
        'snap/Costumes/creature1-b.svg',
        'snap/Costumes/creature1-c.svg',
        'snap/Costumes/cymbal-a.svg',
        'snap/Costumes/cymbal-b.svg',
        'snap/Costumes/dan-a.png',
        'snap/Costumes/dan-b.png',
        'snap/Costumes/dani-a.svg',
        'snap/Costumes/dani-b.svg',
        'snap/Costumes/dani-c.svg',
        'snap/Costumes/dee-a.svg',
        'snap/Costumes/dee-b.svg',
        'snap/Costumes/dee-c.svg',
        'snap/Costumes/dee-d.svg',
        'snap/Costumes/dee-e.svg',
        'snap/Costumes/devin-a.svg',
        'snap/Costumes/devin-b.svg',
        'snap/Costumes/devin-c.svg',
        'snap/Costumes/devin-d.svg',
        'snap/Costumes/dinosaur1-a.svg',
        'snap/Costumes/dinosaur1-b.svg',
        'snap/Costumes/dinosaur1-c.svg',
        'snap/Costumes/dinosaur1-d.svg',
        'snap/Costumes/dinosaur1-e.svg',
        'snap/Costumes/dinosaur1-f.svg',
        'snap/Costumes/dinosaur1-g.svg',
        'snap/Costumes/dinosaur2-a.svg',
        'snap/Costumes/dinosaur2-b.svg',
        'snap/Costumes/dinosaur3.svg',
        'snap/Costumes/diver1.svg',
        'snap/Costumes/diver2.svg',
        'snap/Costumes/dm_freeze.png',
        'snap/Costumes/dm_pop_down.png',
        'snap/Costumes/dm_pop_front.png',
        'snap/Costumes/dm_pop_L_arm.png',
        'snap/Costumes/dm_pop_left.png',
        'snap/Costumes/dm_pop_R_arm.png',
        'snap/Costumes/dm_pop_right.png',
        'snap/Costumes/dm_pop_stand.png',
        'snap/Costumes/dm_stance.svg',
        'snap/Costumes/dm_top_L_leg.png',
        'snap/Costumes/dm_top_R_leg.png',
        'snap/Costumes/dm_top_stand.png',
        'snap/Costumes/dog1-a.svg',
        'snap/Costumes/dog1-b.svg',
        'snap/Costumes/dog2-a.svg',
        'snap/Costumes/dog2-b.svg',
        'snap/Costumes/dog2-c.svg',
        'snap/Costumes/dog_puppy_back.png',
        'snap/Costumes/dog_puppy_right.png',
        'snap/Costumes/dog_puppy_side.png',
        'snap/Costumes/dog_puppy_sit.png',
        'snap/Costumes/donut.svg',
        'snap/Costumes/dove1-a.svg',
        'snap/Costumes/dove1-b.svg',
        'snap/Costumes/dove2-a.svg',
        'snap/Costumes/dove2-b.svg',
        'snap/Costumes/dragon1-a.svg',
        'snap/Costumes/dragon1-b.png',
        'snap/Costumes/dragon1-b.svg',
        'snap/Costumes/dragon2.gif',
        'snap/Costumes/drum1-a.svg',
        'snap/Costumes/drum1-b.svg',
        'snap/Costumes/drum2-a.svg',
        'snap/Costumes/drum2-b.svg',
        'snap/Costumes/drum_bass-a.svg',
        'snap/Costumes/drum_bass-b.svg',
        'snap/Costumes/drums_conga-a.svg',
        'snap/Costumes/drums_conga-b.svg',
        'snap/Costumes/drum_snare-a.svg',
        'snap/Costumes/drum_snare-b.svg',
        'snap/Costumes/duck.svg',
        'snap/Costumes/earth.svg',
        'snap/Costumes/elephant-a_.svg',
        'snap/Costumes/elephant-b_.svg',
        'snap/Costumes/fire_hydrant.png',
        'snap/Costumes/fish1.svg',
        'snap/Costumes/fish2.svg',
        'snap/Costumes/fish3.svg',
        'snap/Costumes/flower_shape.svg',
        'snap/Costumes/football_running.png',
        'snap/Costumes/football_standing.png',
        'snap/Costumes/fortunecookie.png',
        'snap/Costumes/fox.svg',
        'snap/Costumes/frog.svg',
        'snap/Costumes/fruit_platter.png',
        'snap/Costumes/fruitsalad.svg',
        'snap/Costumes/ghost1_.svg',
        'snap/Costumes/ghost2-a.svg',
        'snap/Costumes/ghost2-b.svg',
        'snap/Costumes/ghoul-a.svg',
        'snap/Costumes/ghoul-b.svg',
        'snap/Costumes/gift-a.svg',
        'snap/Costumes/gift-b.svg',
        'snap/Costumes/girl1-standing.gif',
        'snap/Costumes/girl1-walking.gif',
        'snap/Costumes/girl2-shouting.gif',
        'snap/Costumes/girl2-standing.gif',
        'snap/Costumes/girl3-basketball.gif',
        'snap/Costumes/girl3-running.gif',
        'snap/Costumes/girl3-standing.gif',
        'snap/Costumes/glasses.svg',
        'snap/Costumes/glass_water-a.svg',
        'snap/Costumes/glass_water-b.svg',
        'snap/Costumes/green_flag.svg',
        'snap/Costumes/guitar_bass.svg',
        'snap/Costumes/guitar_electric.svg',
        'snap/Costumes/guitar.svg',
        'snap/Costumes/hannah-a.png',
        'snap/Costumes/hannah-b.png',
        'snap/Costumes/hannah-c.png',
        'snap/Costumes/hat_beanie.svg',
        'snap/Costumes/hat_party2-a.svg',
        'snap/Costumes/Hat.svg',
        'snap/Costumes/hat_winter.svg',
        'snap/Costumes/hat_wizard.svg',
        'snap/Costumes/headband.svg',
        'snap/Costumes/heart_code.svg',
        'snap/Costumes/heart_face.svg',
        'snap/Costumes/heart_love_it.svg',
        'snap/Costumes/heart_purple.svg',
        'snap/Costumes/heart_red.svg',
        'snap/Costumes/heart_smile.svg',
        'snap/Costumes/heart_sweet.svg',
        'snap/Costumes/helicopter.png',
        'snap/Costumes/hippo1-a.svg',
        'snap/Costumes/hippo1-b.svg',
        'snap/Costumes/holly1.svg',
        'snap/Costumes/holly2.svg',
        'snap/Costumes/home_button.svg',
        'snap/Costumes/horse1-a.svg',
        'snap/Costumes/horse1-b.svg',
        'snap/Costumes/jaime-a.png',
        'snap/Costumes/jaime-b.png',
        'snap/Costumes/jaime_walking-a.png',
        'snap/Costumes/jaime_walking-b.png',
        'snap/Costumes/jaime_walking-c.png',
        'snap/Costumes/jaime_walking-d.png',
        'snap/Costumes/jaime_walking-e.png',
        'snap/Costumes/jay.gif',
        'snap/Costumes/jeans-a.svg',
        'snap/Costumes/jeans-b.svg',
        'snap/Costumes/jodi.gif',
        'snap/Costumes/jo_pop_down.png',
        'snap/Costumes/jo_pop_front.png',
        'snap/Costumes/jo_pop_L_arm.png',
        'snap/Costumes/jo_pop_left.png',
        'snap/Costumes/jo_pop_R_arm.png',
        'snap/Costumes/jo_pop_right.png',
        'snap/Costumes/jo_pop_stand.png',
        'snap/Costumes/jo_stance.png',
        'snap/Costumes/jo_top_L_cross.png',
        'snap/Costumes/jo_top_L_leg.png',
        'snap/Costumes/jo_top_R_cross.png',
        'snap/Costumes/jo_top_R_leg.png',
        'snap/Costumes/jo_top_stand.png',
        'snap/Costumes/keyboard-a.svg',
        'snap/Costumes/keyboard-b.svg',
        'snap/Costumes/keyboard-c.svg',
        'snap/Costumes/keyboard-d.svg',
        'snap/Costumes/key.svg',
        'snap/Costumes/khalid-a.png',
        'snap/Costumes/Khalid-b.png',
        'snap/Costumes/khalid-c.png',
        'snap/Costumes/khalid-d.png',
        'snap/Costumes/knight.svg',
        'snap/Costumes/ladybug2-a.svg',
        'snap/Costumes/ladybug2-b.svg',
        'snap/Costumes/ladybug2.svg',
        'snap/Costumes/lamp.png',
        'snap/Costumes/laptop.svg',
        'snap/Costumes/lb_pop_down.png',
        'snap/Costumes/lb_pop_front.png',
        'snap/Costumes/lb_pop_L_arm.png',
        'snap/Costumes/lb_pop_left.png',
        'snap/Costumes/lb_pop_R_arm.png',
        'snap/Costumes/lb_pop_right.png',
        'snap/Costumes/lb_pop_stand.png',
        'snap/Costumes/lb_stance.png',
        'snap/Costumes/lb_top_L_cross.png',
        'snap/Costumes/lb_top_L_leg.png',
        'snap/Costumes/lb_top_R_cross.png',
        'snap/Costumes/lb_top_R_leg.png',
        'snap/Costumes/lb_top_stand.png',
        'snap/Costumes/lightning.svg',
        'snap/Costumes/lion-a.svg',
        'snap/Costumes/lion-b.svg',
        'snap/Costumes/lioness.svg',
        'snap/Costumes/lorenz01.png',
        'snap/Costumes/lorenz02.png',
        'snap/Costumes/lorenz03.png',
        'snap/Costumes/lorenz04.png',
        'snap/Costumes/lorenz05.png',
        'snap/Costumes/lorenz06.png',
        'snap/Costumes/lorenz07b.png',
        'snap/Costumes/lorenz07.png',
        'snap/Costumes/magiccarpet.png',
        'snap/Costumes/magicwand.svg',
        'snap/Costumes/marble-building.png',
        'snap/Costumes/marissa-crouching.gif',
        'snap/Costumes/marissa.gif',
        'snap/Costumes/marissa-sitting.gif',
        'snap/Costumes/maya.png',
        'snap/Costumes/microphonestand.svg',
        'snap/Costumes/microphone.svg',
        'snap/Costumes/monkey1-a.svg',
        'snap/Costumes/monkey1-b.svg',
        'snap/Costumes/monkey2-a.svg',
        'snap/Costumes/monkey2-b.svg',
        'snap/Costumes/monkey2-c.svg',
        'snap/Costumes/mori.png',
        'snap/Costumes/mouse1-a.svg',
        'snap/Costumes/mouse1-b.svg',
        'snap/Costumes/muffin-a.svg',
        'snap/Costumes/muffin-b.svg',
        'snap/Costumes/octopus-a.svg',
        'snap/Costumes/octopus-b.svg',
        'snap/Costumes/orange2-a.svg',
        'snap/Costumes/orange2-b.svg',
        'snap/Costumes/orange2-c.svg',
        'snap/Costumes/orange.svg',
        'snap/Costumes/paddle.svg',
        'snap/Costumes/palmtree.gif',
        'snap/Costumes/parrot2-a.svg',
        'snap/Costumes/parrot2-b.svg',
        'snap/Costumes/parrot-a.svg',
        'snap/Costumes/parrot-b.svg',
        'snap/Costumes/partyhat1.svg',
        'snap/Costumes/paul.gif',
        'snap/Costumes/pencil-a.svg',
        'snap/Costumes/pencil-b.svg',
        'snap/Costumes/penguin1.svg',
        'snap/Costumes/penguin1_talk-a.svg',
        'snap/Costumes/penguin1_talk-b.svg',
        'snap/Costumes/penguin2.svg',
        'snap/Costumes/penguin2_talk-a.svg',
        'snap/Costumes/penguin2_talk-b.svg',
        'snap/Costumes/penguin3-a.svg',
        'snap/Costumes/penguin3-b.svg',
        'snap/Costumes/penguin3-c.svg',
        'snap/Costumes/piano.svg',
        'snap/Costumes/planet2.svg',
        'snap/Costumes/princess.svg',
        'snap/Costumes/prince.svg',
        'snap/Costumes/rainbow.svg',
        'snap/Costumes/referee.gif',
        'snap/Costumes/reindeer.svg',
        'snap/Costumes/robot1.svg',
        'snap/Costumes/rocks.svg',
        'snap/Costumes/rory.png',
        'snap/Costumes/ruby-a.png',
        'snap/Costumes/ruby-b.png',
        'snap/Costumes/sail-boat.png',
        'snap/Costumes/sam.gif',
        'snap/Costumes/saxophone-a.svg',
        'snap/Costumes/saxophone-b.svg',
        'snap/Costumes/scarf1.svg',
        'snap/Costumes/scarf2.svg',
        'snap/Costumes/shark-a_.svg',
        'snap/Costumes/shark-b_.svg',
        'snap/Costumes/shark-c_.svg',
        'snap/Costumes/shirt2-a2.svg',
        'snap/Costumes/shirt2-a.svg',
        'snap/Costumes/shirt-a.svg',
        'snap/Costumes/shirt_blouse.svg',
        'snap/Costumes/shirt-b.svg',
        'snap/Costumes/shirt_collar-a.svg',
        'snap/Costumes/shirt_collar-b.svg',
        'snap/Costumes/shirt_collar-c.svg',
        'snap/Costumes/shoes1.svg',
        'snap/Costumes/shoes2.svg',
        'snap/Costumes/Singer1.svg',
        'snap/Costumes/skates.svg',
        'snap/Costumes/sl_pop_L_arm.png',
        'snap/Costumes/sl_pop_R_arm.png',
        'snap/Costumes/sl_top_L_cross.png',
        'snap/Costumes/sl_top_L_leg.png',
        'snap/Costumes/sl_top_R_cross.png',
        'snap/Costumes/sl_top_ready.png',
        'snap/Costumes/sl_top_R_leg.png',
        'snap/Costumes/sl_top_stand.png',
        'snap/Costumes/snowflake.svg',
        'snap/Costumes/snowman.svg',
        'snap/Costumes/spaceship-a.svg',
        'snap/Costumes/spaceship-b.svg',
        'snap/Costumes/speaker.svg',
        'snap/Costumes/squirrel1.png',
        'snap/Costumes/star1.svg',
        'snap/Costumes/star2.svg',
        'snap/Costumes/star3-a.svg',
        'snap/Costumes/star3-b.svg',
        'snap/Costumes/starfish-a.svg',
        'snap/Costumes/starfish-b_.svg',
        'snap/Costumes/stop.svg',
        'snap/Costumes/street-cleaner-mit.png',
        'snap/Costumes/sunglasses1.svg',
        'snap/Costumes/sunglasses2.svg',
        'snap/Costumes/sun.svg',
        'snap/Costumes/tabla-a.svg',
        'snap/Costumes/tabla-b.svg',
        'snap/Costumes/taco-a.svg',
        'snap/Costumes/taco-b.svg',
        'snap/Costumes/tennisball.png',
        'snap/Costumes/trampoline.png',
        'snap/Costumes/tree1.svg',
        'snap/Costumes/tree2.svg',
        'snap/Costumes/tree-lights-a.svg',
        'snap/Costumes/tree-lights-b.svg',
        'snap/Costumes/trees-a.svg',
        'snap/Costumes/trees-b.svg',
        'snap/Costumes/trombone-a.svg',
        'snap/Costumes/trombone-b.svg',
        'snap/Costumes/trumpet-a2.svg',
        'snap/Costumes/trumpet-a.svg',
        'snap/Costumes/ukulele.svg',
        'snap/Costumes/umbrella.png',
        'snap/Costumes/unicorn1.png',
        'snap/Costumes/unicorn.svg',
        'snap/Costumes/vest-a.svg',
        'snap/Costumes/vest-b.svg',
        'snap/Costumes/wanda.svg',
        'snap/Costumes/watermelon-a.svg',
        'snap/Costumes/watermelon-b.svg',
        'snap/Costumes/watermelon-c.svg',
        'snap/Costumes/witch.svg',
        'snap/Costumes/wizard1.svg',
        'snap/Costumes/wizard2.svg',
        'snap/Costumes/wizard.svg',

        // Backgrounds
        'snap/Backgrounds/BACKGROUNDS',

        'snap/Backgrounds/atom_playground.jpg',
        'snap/Backgrounds/bedroom1.gif',
        'snap/Backgrounds/bedroom2.gif',
        'snap/Backgrounds/berkeley_mural.jpg',
        'snap/Backgrounds/brick-wall-and-stairs.jpg',
        'snap/Backgrounds/brick-wall1.jpg',
        'snap/Backgrounds/brick-wall2.jpg',
        'snap/Backgrounds/desert.gif',
        'snap/Backgrounds/night_city_with_street.gif',
        'snap/Backgrounds/party_room.jpg',
        'snap/Backgrounds/pathway.jpg',
        'snap/Backgrounds/xy-grid.gif',
        
        // Sounds
        'snap/Sounds/SOUNDS',

        'snap/Sounds/Cat.mp3',
        'snap/Sounds/Chord.wav',
        'snap/Sounds/Dog1.wav',
        'snap/Sounds/Dog2.wav',
        'snap/Sounds/FingerSnap.wav',
        'snap/Sounds/Kitten.wav',
        'snap/Sounds/Laugh-female.wav',
        'snap/Sounds/Laugh-male1.wav',
        'snap/Sounds/Laugh-male2.wav',
        'snap/Sounds/Laugh-male3.mp3',
        'snap/Sounds/Meow.wav',
        'snap/Sounds/Pop.wav',
        
        // Examples
        'snap/Examples/EXAMPLES',

        'snap/Examples/animal-game.xml',
        'snap/Examples/Codification.xml',
        'snap/Examples/copter.xml',
        'snap/Examples/count-change.xml',
        'snap/Examples/icecream-visual.xml',
        'snap/Examples/JSfunctions.xml',
        'snap/Examples/live-tree.xml',
        'snap/Examples/swimmer.xml',
        'snap/Examples/tree.xml',
        'snap/Examples/vee.xml',


// additions by Ken Kahn for ecraft2learn blocks
'js/onload.js',
'ecraft2learn.js',
'index.html',
'AI-Teacher-Guide/chapter-1.html',
'AI-Teacher-Guide/chapter-2.html',
'AI-Teacher-Guide/chapter-3.html',
'AI-Teacher-Guide/chapter-4.html',
'AI-Teacher-Guide/chapter-5.html',
'AI-Teacher-Guide/chapter-6.html',
'AI-Teacher-Guide/listening%20blocks.xml',
'AI-Teacher-Guide/misc%20AI%20blocks.xml',
'AI-Teacher-Guide/neural%20nets%20blocks.xml',
'AI-Teacher-Guide/seeing%20blocks.xml',
'AI-Teacher-Guide/speaking%20blocks.xml',
'AI-Teacher-Guide/troubleshooting.html',
'AI-Teacher-Guide/words%20blocks.xml',
'AI-Teacher-Guide/images/AI%20Questions.png',
'AI-Teacher-Guide/images/aligning-word-embeddings.png',
'AI-Teacher-Guide/images/ask-wikipedia-program.png',
'AI-Teacher-Guide/images/better%20machine%20learning%20exercise.png',
'AI-Teacher-Guide/images/black%20and%20white.png',
'AI-Teacher-Guide/images/camera%20and%20say.png',
'AI-Teacher-Guide/images/camera%20train.png',
'AI-Teacher-Guide/images/camera,%20listen,%20and%20speak%20no%20keys.png',
'AI-Teacher-Guide/images/cats%20and%20dogs.png',
'AI-Teacher-Guide/images/closest%20word%20to.png',
'AI-Teacher-Guide/images/command-program.png',
'AI-Teacher-Guide/images/command.png',
'AI-Teacher-Guide/images/complex%20listen%20block.png',
'AI-Teacher-Guide/images/confidence%20guesser.png',
'AI-Teacher-Guide/images/confidence.png',
'AI-Teacher-Guide/images/dates.png',
'AI-Teacher-Guide/images/detect%20objects%20exercise.png',
'AI-Teacher-Guide/images/detect%20objects%20options.png',
'AI-Teacher-Guide/images/doorbell%20fix.png',
'AI-Teacher-Guide/images/doorbell%20problem.png',
'AI-Teacher-Guide/images/draw%20word%20embedding.png',
'AI-Teacher-Guide/images/edges%20layer.png',
'AI-Teacher-Guide/images/features%20of.png',
'AI-Teacher-Guide/images/follow%20finger%20exercise.png',
'AI-Teacher-Guide/images/follow%20finger.png',
'AI-Teacher-Guide/images/grrrrrrr.png',
'AI-Teacher-Guide/images/guess%20my%20word.png',
'AI-Teacher-Guide/images/hawking.jpg',
'AI-Teacher-Guide/images/hyperparameters%20exercise.png',
'AI-Teacher-Guide/images/image%20embedding%20exercise.png',
'AI-Teacher-Guide/images/image%20labels%20reporter%20and%20show%20photo.png',
'AI-Teacher-Guide/images/image%20labels%20reporter.png',
'AI-Teacher-Guide/images/importing-data.png',
'AI-Teacher-Guide/images/kahn%20photo.jpg',
'AI-Teacher-Guide/images/listen%20error.png',
'AI-Teacher-Guide/images/load%20models%20and%20data.png',
'AI-Teacher-Guide/images/load%20neural%20net.png',
'AI-Teacher-Guide/images/load%20training%20data.png',
'AI-Teacher-Guide/images/load%20training.png',
'AI-Teacher-Guide/images/machine%20learning%20exercise.png',
'AI-Teacher-Guide/images/Mary%20voices.png',
'AI-Teacher-Guide/images/mobilenet.png',
'AI-Teacher-Guide/images/model-8-9-9-9-4.png',
'AI-Teacher-Guide/images/naming%20colors.png',
'AI-Teacher-Guide/images/noisy%20polygon.png',
'AI-Teacher-Guide/images/numbers%20signs.png',
'AI-Teacher-Guide/images/objects%20layer.png',
'AI-Teacher-Guide/images/part%20of%20speech%20broadcast.png',
'AI-Teacher-Guide/images/part-of-speech-code.png',
'AI-Teacher-Guide/images/part-of-speech-when-something-heard.png',
'AI-Teacher-Guide/images/parts%20layer.png',
'AI-Teacher-Guide/images/patterns%20layer.png',
'AI-Teacher-Guide/images/popup-blocked.png',
'AI-Teacher-Guide/images/popup-dialog.png',
'AI-Teacher-Guide/images/pose.png',
'AI-Teacher-Guide/images/projector-bookmarks.png',
'AI-Teacher-Guide/images/question%20answer.png',
'AI-Teacher-Guide/images/random%20word%20locations.png',
'AI-Teacher-Guide/images/rate%20pitch%20volume.png',
'AI-Teacher-Guide/images/read%20problem.png',
'AI-Teacher-Guide/images/recognize%20asynchronous.png',
'AI-Teacher-Guide/images/recognize%20new%20photo.png',
'AI-Teacher-Guide/images/rock%20paper%20scissors.png',
'AI-Teacher-Guide/images/save-your-training.png',
'AI-Teacher-Guide/images/segmentation%20multi.png',
'AI-Teacher-Guide/images/segmentation%20single%20script.png',
'AI-Teacher-Guide/images/segmentation%20single.png',
'AI-Teacher-Guide/images/segmentation.png',
'AI-Teacher-Guide/images/sentence%20embedding.png',
'AI-Teacher-Guide/images/separate%20words.png',
'AI-Teacher-Guide/images/show-blocks.png',
'AI-Teacher-Guide/images/simon%20says.png',
'AI-Teacher-Guide/images/simple%20listen%20block.png',
'AI-Teacher-Guide/images/simple%20speak%20block.png',
'AI-Teacher-Guide/images/snap-costume.png',
'AI-Teacher-Guide/images/sort%20closest%20words.png',
'AI-Teacher-Guide/images/speak%20randomly.png',
'AI-Teacher-Guide/images/story%20generator.png',
'AI-Teacher-Guide/images/style%20transfer%20exercise.png',
'AI-Teacher-Guide/images/style%20transfer.png',
'AI-Teacher-Guide/images/sub-list-icon.png',
'AI-Teacher-Guide/images/TB010-Deep-Neural-Network.jpg',
'AI-Teacher-Guide/images/teachable%20machine%20exercise.png',
'AI-Teacher-Guide/images/textures%20layer.png',
'AI-Teacher-Guide/images/tic-tac-toe-board.png',
'AI-Teacher-Guide/images/tinkertoy-tic-tac-toe-X39.81.03.jpg',
'AI-Teacher-Guide/images/train%20and%20speak%20commands.png',
'AI-Teacher-Guide/images/train%20audio.png',
'AI-Teacher-Guide/images/training-buttons.png',
'AI-Teacher-Guide/images/translate%20exercise.png',
'AI-Teacher-Guide/images/translate.png',
'AI-Teacher-Guide/images/voices.png',
'AI-Teacher-Guide/images/weather%20exercise.png',
'AI-Teacher-Guide/images/weather.png',
'AI-Teacher-Guide/images/Wikipedia%20answers.png',
'AI-Teacher-Guide/images/word%20analogy%20bias.png',
'AI-Teacher-Guide/images/word%20analogy.png',
'AI-Teacher-Guide/images/word%20average.png',
'AI-Teacher-Guide/images/word%20line.png',
'AI-Teacher-Guide/images/xkcd-machine-learning.png',
'AI-Teacher-Guide/images/young-donald-knuth-ibm-650-1958.jpg',
'camera-train/train-mobilenet.js',
'camera-train/index.html',
'projects/AI%20Questions.xml',
'projects/animate%20style.xml',
'projects/balloon%20game.xml',
'projects/better%20machine%20learning%20exercise.xml',
'projects/black%20and%20white.xml',
'projects/camera%20and%20say%20no%20keys.xml',
'projects/camera%20and%20say.xml',
'projects/camera,%20listen,%20and%20speak%20no%20keys.xml',
'projects/camera%20train.xml',
'projects/cats%20and%20dogs.xml',
'projects/closest%20word%20to.xml',
'projects/codenames.xml',
'projects/command%20broadcast%202.xml',
'projects/command%20sentences.xml',
'projects/command.xml',
'projects/complex%20listen%20block.xml',
'projects/confidence%20guesser.xml',
'projects/confidence.xml',
'projects/dates.xml',
'projects/detect%20objects%20exercise.xml',
'projects/detect%20objects.xml',
'projects/dont%20touch%20your%20face.xml',
'projects/doorbell%20fix.xml',
'projects/doorbell%20problem.xml',
'projects/draw%20sentence%20embedding.xml',
'projects/draw%20word%20embedding.xml',
'projects/features%20of.xml',
'projects/follow%20finger%20exercise.xml',
'projects/follow%20finger.xml',
'projects/follow%20lean.xml',
'projects/grrrrrrr.xml',
'projects/guess%20my%20word.xml',
'projects/hyperparameters%20exercise.xml',
'projects/image%20embedding%20exercise.xml',
'projects/image%20embedding.xml',
'projects/image%20labels%20reporter%20and%20show%20photo.xml',
'projects/image%20labels%20reporter.xml',
'projects/listen%20error.xml',
'projects/listening.xml',
'projects/load%20neural%20net.xml',
'projects/load%20training%20data.xml',
'projects/load%20training.xml',
'projects/machine%20learning%20exercise.xml',
'projects/Mary%20voices.xml',
'projects/misc%20AI.xml',
'projects/mobilenet.xml',
'projects/naming%20colors.xml',
'projects/neural%20nets.xml',
'projects/noisy%20polygon.xml',
'projects/numbers%20signs.xml',
'projects/part%20of%20speech%20broadcast.xml',
'projects/part%20of%20speech.xml',
'projects/pose.xml',
'projects/predict%20function.xml',
'projects/predict%20sequence.xml',
'projects/question%20answer.xml',
'projects/random%20word%20locations.xml',
'projects/rate%20pitch%20volume.xml',
'projects/read%20problem.xml',
'projects/recognize%20asynchronous.xml',
'projects/recognize%20new%20photo.xml',
'projects/rock%20paper%20scissors.xml',
'projects/seeing.xml',
'projects/segmentation%20multi.xml',
'projects/segmentation%20single.xml',
'projects/sensors%20rover.xml',
'projects/sentence%20embedding.xml',
'projects/separate%20words.xml',
'projects/simon%20says.xml',
'projects/simple%20listen%20block.xml',
'projects/simple%20speak%20block.xml',
'projects/sort%20closest%20words.xml',
'projects/speaking.xml',
'projects/speak%20randomly.xml',
'projects/story%20generator.xml',
'projects/style%20transfer%20exercise.xml',
'projects/style%20transfer.xml',
'projects/teachable%20machine%20exercise.xml',
'projects/text%20to%20bignum.xml',
'projects/tic%20tac%20toe%20machine%20learning.xml',
'projects/tic%20tac%20toe.xml',
'projects/train%20and%20speak%20commands.xml',
'projects/train%20audio.xml',
'projects/translate%20exercise.xml',
'projects/translate.xml',
'projects/voices.xml',
'projects/weather%20data.xml',
'projects/weather%20exercise.xml',
'projects/weather.xml',
'projects/Wikipedia%20answers.xml',
'projects/word%20analogy%20bias.xml',
'projects/word%20analogy%20search.xml',
'projects/word%20analogy%20use.xml',
'projects/word%20analogy.xml',
'projects/word%20average.xml',
'projects/word%20bias.xml',
'projects/words.xml',
'css/ai-teacher-guide.css',
'css/non-essential.css',
'css/oer-style.css',
'css/student.css',
'css/teacher.css',
'detection/detection.js',
'detection/index.html',
'detection/ssd_mobilenet_v2/group1-shard10of17',
'detection/ssd_mobilenet_v2/group1-shard11of17',
'detection/ssd_mobilenet_v2/group1-shard12of17',
'detection/ssd_mobilenet_v2/group1-shard13of17',
'detection/ssd_mobilenet_v2/group1-shard14of17',
'detection/ssd_mobilenet_v2/group1-shard15of17',
'detection/ssd_mobilenet_v2/group1-shard16of17',
'detection/ssd_mobilenet_v2/group1-shard17of17',
'detection/ssd_mobilenet_v2/group1-shard1of17',
'detection/ssd_mobilenet_v2/group1-shard2of17',
'detection/ssd_mobilenet_v2/group1-shard3of17',
'detection/ssd_mobilenet_v2/group1-shard4of17',
'detection/ssd_mobilenet_v2/group1-shard5of17',
'detection/ssd_mobilenet_v2/group1-shard6of17',
'detection/ssd_mobilenet_v2/group1-shard7of17',
'detection/ssd_mobilenet_v2/group1-shard8of17',
'detection/ssd_mobilenet_v2/group1-shard9of17',
'detection/ssd_mobilenet_v2/model.json',
'detection/ssdlite_mobilenet_v2/group1-shard1of5',
'detection/ssdlite_mobilenet_v2/group1-shard2of5',
'detection/ssdlite_mobilenet_v2/group1-shard3of5',
'detection/ssdlite_mobilenet_v2/group1-shard4of5',
'detection/ssdlite_mobilenet_v2/group1-shard5of5',
'detection/ssdlite_mobilenet_v2/model.json',
'js/acknowledgements.js',
'js/ai-guide.js',
'js/body-pix.js',
'js/bottom-of-page.js',
'js/coco-ssd.js',
'js/crypto-js.js',
'js/dat.gui.js',
'js/ecraft2learn_snap_extension.js',
'js/filter_images.js',
'js/hyperparameters.js',
'js/hyperparameters.min.js',
'js/invoke_callback.js',
'js/knn-classifier.js',
'js/load-scripts.js',
'js/mobilenet.js',
'js/plainwebrtc.js',
'js/posenet.js',
'js/snap_or_isnap.js',
'js/stats.min.js',
'js/teachablemachine-image.min.js',
'js/tf.min.js.map',
'js/tfjs-vis.js',
'js/tfjs-vis.umd.min.js.map',
'js/tfjs.js',
'js/train-report-results.js',
'js/train.js',
'js/training-utilities.js',
'js/translate.js',
'js/universal-sentence-encoder.js',
'js/user-agent.js',
'js/webrtc.js',
'js/mobilenet_v1_1.0_224/group1-shard1of1',
'js/mobilenet_v1_1.0_224/group10-shard1of1',
'js/mobilenet_v1_1.0_224/group11-shard1of1',
'js/mobilenet_v1_1.0_224/group12-shard1of1',
'js/mobilenet_v1_1.0_224/group13-shard1of1',
'js/mobilenet_v1_1.0_224/group14-shard1of1',
'js/mobilenet_v1_1.0_224/group15-shard1of1',
'js/mobilenet_v1_1.0_224/group16-shard1of1',
'js/mobilenet_v1_1.0_224/group17-shard1of1',
'js/mobilenet_v1_1.0_224/group18-shard1of1',
'js/mobilenet_v1_1.0_224/group19-shard1of1',
'js/mobilenet_v1_1.0_224/group2-shard1of1',
'js/mobilenet_v1_1.0_224/group20-shard1of1',
'js/mobilenet_v1_1.0_224/group21-shard1of1',
'js/mobilenet_v1_1.0_224/group22-shard1of1',
'js/mobilenet_v1_1.0_224/group23-shard1of1',
'js/mobilenet_v1_1.0_224/group24-shard1of1',
'js/mobilenet_v1_1.0_224/group25-shard1of1',
'js/mobilenet_v1_1.0_224/group26-shard1of1',
'js/mobilenet_v1_1.0_224/group27-shard1of1',
'js/mobilenet_v1_1.0_224/group28-shard1of1',
'js/mobilenet_v1_1.0_224/group29-shard1of1',
'js/mobilenet_v1_1.0_224/group3-shard1of1',
'js/mobilenet_v1_1.0_224/group30-shard1of1',
'js/mobilenet_v1_1.0_224/group31-shard1of1',
'js/mobilenet_v1_1.0_224/group32-shard1of1',
'js/mobilenet_v1_1.0_224/group33-shard1of1',
'js/mobilenet_v1_1.0_224/group34-shard1of1',
'js/mobilenet_v1_1.0_224/group35-shard1of1',
'js/mobilenet_v1_1.0_224/group36-shard1of1',
'js/mobilenet_v1_1.0_224/group37-shard1of1',
'js/mobilenet_v1_1.0_224/group38-shard1of1',
'js/mobilenet_v1_1.0_224/group39-shard1of1',
'js/mobilenet_v1_1.0_224/group4-shard1of1',
'js/mobilenet_v1_1.0_224/group40-shard1of1',
'js/mobilenet_v1_1.0_224/group41-shard1of1',
'js/mobilenet_v1_1.0_224/group42-shard1of1',
'js/mobilenet_v1_1.0_224/group43-shard1of1',
'js/mobilenet_v1_1.0_224/group44-shard1of1',
'js/mobilenet_v1_1.0_224/group45-shard1of1',
'js/mobilenet_v1_1.0_224/group46-shard1of1',
'js/mobilenet_v1_1.0_224/group47-shard1of1',
'js/mobilenet_v1_1.0_224/group48-shard1of1',
'js/mobilenet_v1_1.0_224/group49-shard1of1',
'js/mobilenet_v1_1.0_224/group5-shard1of1',
'js/mobilenet_v1_1.0_224/group50-shard1of1',
'js/mobilenet_v1_1.0_224/group51-shard1of1',
'js/mobilenet_v1_1.0_224/group52-shard1of1',
'js/mobilenet_v1_1.0_224/group53-shard1of1',
'js/mobilenet_v1_1.0_224/group54-shard1of1',
'js/mobilenet_v1_1.0_224/group55-shard1of1',
'js/mobilenet_v1_1.0_224/group6-shard1of1',
'js/mobilenet_v1_1.0_224/group7-shard1of1',
'js/mobilenet_v1_1.0_224/group8-shard1of1',
'js/mobilenet_v1_1.0_224/group9-shard1of1',
'js/mobilenet_v1_1.0_224/model.json',
'js/mobilenet_v2_100_224/classification/2/group1-shard1of4',
'js/mobilenet_v2_100_224/classification/2/group1-shard2of4',
'js/mobilenet_v2_100_224/classification/2/group1-shard3of4',
'js/mobilenet_v2_100_224/classification/2/group1-shard4of4',
'js/mobilenet_v2_100_224/classification/2/model.json',
'help/AI%20QnA%20explanation.html',
'help/hyperparameter-search.html',
'help/images/hyperparameter-search.png',
'images/4%20machine%20learning%20projects.png',
'images/88x31.png',
'images/AI%20Questions.png',
'images/all-means-vs-animal-means.png',
'images/animal-means-vs-50-random-words-black-red.png',
'images/animal-means-vs-50-random-words-red-yellow.png',
'images/animal-means-vs-50-random-words.png',
'images/balloon%20game.png',
'images/camera%20and%20say%20no%20keys.png',
'images/camera,%20listen,%20and%20speak%20no%20keys.png',
'images/codenames.png',
'images/command%20broadcast%202.png',
'images/command%20sentences.png',
'images/confidence%20guesser.png',
'images/detect%20objects.png',
'images/dont%20touch%20your%20face.png',
'images/eCraft2Learn-Favicon.png',
'images/eCraft2Learn-Final0.1.png',
'images/eCraftLogo.png',
'images/follow%20finger.png',
'images/follow%20lean.png',
'images/grrrrrrrr.png',
'images/guess%20my%20word.png',
'images/i%20give%20up.png',
'images/image%20analogy.png',
'images/Logo_eCraft2Learn.png',
'images/logo_ecraft_face.png',
'images/logo_EU_flag.png',
'images/Logo_EU_white.png',
'images/Logo_PD.png',
'images/love-vs-50-random-words.png',
'images/naming-colors.png',
'images/noisy%20pentagon.png',
'images/other-palette.png',
'images/oxford-crestsq.png',
'images/part%20of%20speech%20broadcast.png',
'images/pentagon.png',
// 'snap/images/pose-detection.gif', // over 14MB
'images/powered-by-yahoo.png',
'images/predict%20function.png',
'images/question%20answer.png',
'images/rock%20paper%20scissors.png',
'images/Rock_paper_scissors.jpg',
'images/sample%20AI%20blocks.png',
'images/segmentation%20demo.png',
'images/segmentation.png',
'images/sensing-palette.png',
'images/simon%20says.png',
'images/sound-palette.png',
'images/speak%20randomly.png',
'images/speech%20input%20button.png',
'images/story%20generator.png',
'images/style%20transfer.png',
'images/tic%20tac%20toe%20machine%20learning.png',
'images/train%20and%20speak%20commands.png',
'images/translate.png',
'images/weather.png',
'images/Wikipedia%20answers.png',
'images/word-line-love-hate-old.png',
'images/style-transfer/Edvard_Munch,_1893,_The_Scream,_oil,_tempera_and_pastel_on_cardboard,_91_x_73_cm,_National_Gallery_of_Norway.jpg',
'images/style-transfer/Invaluable-Roberto-Matta-On-The-Edge-of-a-Dream.jpg',
'images/style-transfer/la-muse_picasso.jpg',
'images/style-transfer/mathura_worldmap.png',
'images/style-transfer/Raft_of_the_Medusa.jpg',
'images/style-transfer/rain-princess-leonid-afremov.jpg',
'images/style-transfer/Tsunami_by_hokusai_19th_century.jpg',
'images/style-transfer/udnie-young-american-girl-1913.jpg',
'microphone-train/adapter.js',
'microphone-train/audio-train.js',
'microphone-train/index.html',
'microphone-train/JsSpeechRecognizer.js',
'microphone-train/LICENSE',
'microphone-train/README.md',
'microphone-train/speech-commands.js',
'microphone-train/speech-commands.min.js',
'microphone-train/speechrec.html',
'microphone-train/test.html',
'microphone-train/test.js',
'microphone-train/train.js',
'mobilenet/classify.js',
'mobilenet/index.html',
'models/AI%20blocks%20QA%20b.json',
'models/AI%20blocks%20QA%20b.weights.bin',
'models/AI%20blocks%20QA.json',
'models/AI%20blocks%20QA.weights.bin',
'models/combined_2.json',
'models/combined_2.weights.bin',
'models/combined_3.json',
'models/combined_3.weights.bin',
'models/combined_4.json',
'models/combined_4.weights.bin',
'models/guess%20relation.json',
'models/guess%20relation.weights.bin',
'models/naming%20colors.json',
'models/naming%20colors.weights.bin',
'noisy-polygons/help.png',
'noisy-polygons/index.html',
'noisy-polygons/main.png',
'noisy-polygons/noisy%20polygons.json',
'noisy-polygons/noisy%20polygons.weights.bin',
'noisy-polygons/project-ideas.html',
'posenet/camera.js',
'posenet/demo_util.js',
'posenet/index.html',
'posenet/pose%20properties.txt',
'posenet/sample.html',
'publications/Ai_programming_Constructionism_2018%20v2.pdf',
'publications/Constructionism%20and%20AI%20history%20and%20future%20v4.pdf',
'publications/Deep%20Learning%20Programming%20by%20All.pdf',
'publications/EC-TEL_2018_source-files_48%20kk%20edits%20changes%20accepted.pdf',
'publications/Learning%20by%20enhancing%20half-baked%20AI%20projects.pdf',
'publications/Programming%20word%20embeddings%20in%20Snap.pdf',
'publications/Snap%20AI%20demo%20for%20EAAAI%202022%20submitted.pdf',
'resources/ask%20wikipedia%20costume.png',
'resources/ecraft2learn%20help%20small.png',
'resources/ecraft2learn%20help.png',
'resources/me.png',
'posenet/mobilenet/models/float/050/group1-shard1of1.bin',
'posenet/mobilenet/models/float/050/model-stride16.json',
'posenet/mobilenet/models/float/050/model-stride8.json',
'posenet/mobilenet/models/float/075/group1-shard1of2.bin',
'posenet/mobilenet/models/float/075/group1-shard2of2.bin',
'posenet/mobilenet/models/float/075/model-stride16.json',
'posenet/mobilenet/models/float/075/model-stride8.json',
// '/posenet/mobilenet/models/float/100/group1-shard1of4.bin',
// '/posenet/mobilenet/models/float/100/group1-shard2of4.bin',
// '/posenet/mobilenet/models/float/100/group1-shard3of4.bin',
// '/posenet/mobilenet/models/float/100/group1-shard4of4.bin',
// '/posenet/mobilenet/models/float/100/model-stride16.json',
// '/posenet/mobilenet/models/float/100/model-stride8.json',
// '/posenet/mobilenet/models/quant1/050/group1-shard1of1.bin',
// '/posenet/mobilenet/models/quant1/050/model-stride16.json',
// '/posenet/mobilenet/models/quant1/050/model-stride8.json',
// '/posenet/mobilenet/models/quant1/075/group1-shard1of1.bin',
// '/posenet/mobilenet/models/quant1/075/model-stride16.json',
// '/posenet/mobilenet/models/quant1/075/model-stride8.json',
// '/posenet/mobilenet/models/quant1/100/group1-shard1of1.bin',
// '/posenet/mobilenet/models/quant1/100/model-stride16.json',
// '/posenet/mobilenet/models/quant1/100/model-stride8.json',
// '/posenet/mobilenet/models/quant2/050/group1-shard1of1.bin',
// '/posenet/mobilenet/models/quant2/050/model-stride16.json',
// '/posenet/mobilenet/models/quant2/050/model-stride8.json',
// '/posenet/mobilenet/models/quant2/075/group1-shard1of1.bin',
// '/posenet/mobilenet/models/quant2/075/model-stride16.json',
// '/posenet/mobilenet/models/quant2/075/model-stride8.json',
// '/posenet/mobilenet/models/quant2/100/group1-shard1of2.bin',
// '/posenet/mobilenet/models/quant2/100/group1-shard2of2.bin',
// '/posenet/mobilenet/models/quant2/100/model-stride16.json',
// '/posenet/mobilenet/models/quant2/100/model-stride8.json',
'segmentation/body_pix.js',
'segmentation/index.html',
'segmentation/part_to_color.txt',
'segmentation/mobilenet/quant2/075/group1-shard1of1.bin',
'segmentation/mobilenet/quant2/075/model-stride16.json',
'segmentation/resnet50/quant2/group1-shard10of12.bin',
'segmentation/resnet50/quant2/group1-shard11of12.bin',
'segmentation/resnet50/quant2/group1-shard12of12.bin',
'segmentation/resnet50/quant2/group1-shard1of12.bin',
'segmentation/resnet50/quant2/group1-shard2of12.bin',
'segmentation/resnet50/quant2/group1-shard3of12.bin',
'segmentation/resnet50/quant2/group1-shard4of12.bin',
'segmentation/resnet50/quant2/group1-shard5of12.bin',
'segmentation/resnet50/quant2/group1-shard6of12.bin',
'segmentation/resnet50/quant2/group1-shard7of12.bin',
'segmentation/resnet50/quant2/group1-shard8of12.bin',
'segmentation/resnet50/quant2/group1-shard9of12.bin',
'segmentation/resnet50/quant2/model-stride32.json',
// '/style-transfer/content.jpg',
// '/style-transfer/customtransfer%20from%20Luie.js',
// '/style-transfer/index.html',
// '/style-transfer/magenta-demo.html',
// '/style-transfer/ml5.min.js',
// '/style-transfer/style-transfer.js',
// '/style-transfer/style.jpg',
// '/style-transfer/models/la_muse/manifest.json',
// '/style-transfer/models/la_muse/Variable',
// '/style-transfer/models/la_muse/Variable_1',
// '/style-transfer/models/la_muse/Variable_10',
// '/style-transfer/models/la_muse/Variable_11',
// '/style-transfer/models/la_muse/Variable_12',
// '/style-transfer/models/la_muse/Variable_13',
// '/style-transfer/models/la_muse/Variable_14',
// '/style-transfer/models/la_muse/Variable_15',
// '/style-transfer/models/la_muse/Variable_16',
// '/style-transfer/models/la_muse/Variable_17',
// '/style-transfer/models/la_muse/Variable_18',
// '/style-transfer/models/la_muse/Variable_19',
// '/style-transfer/models/la_muse/Variable_2',
// '/style-transfer/models/la_muse/Variable_20',
// '/style-transfer/models/la_muse/Variable_21',
// '/style-transfer/models/la_muse/Variable_22',
// '/style-transfer/models/la_muse/Variable_23',
// '/style-transfer/models/la_muse/Variable_24',
// '/style-transfer/models/la_muse/Variable_25',
// '/style-transfer/models/la_muse/Variable_26',
// '/style-transfer/models/la_muse/Variable_27',
// '/style-transfer/models/la_muse/Variable_28',
// '/style-transfer/models/la_muse/Variable_29',
// '/style-transfer/models/la_muse/Variable_3',
// '/style-transfer/models/la_muse/Variable_30',
// '/style-transfer/models/la_muse/Variable_31',
// '/style-transfer/models/la_muse/Variable_32',
// '/style-transfer/models/la_muse/Variable_33',
// '/style-transfer/models/la_muse/Variable_34',
// '/style-transfer/models/la_muse/Variable_35',
// '/style-transfer/models/la_muse/Variable_36',
// '/style-transfer/models/la_muse/Variable_37',
// '/style-transfer/models/la_muse/Variable_38',
// '/style-transfer/models/la_muse/Variable_39',
// '/style-transfer/models/la_muse/Variable_4',
// '/style-transfer/models/la_muse/Variable_40',
// '/style-transfer/models/la_muse/Variable_41',
// '/style-transfer/models/la_muse/Variable_42',
// '/style-transfer/models/la_muse/Variable_43',
// '/style-transfer/models/la_muse/Variable_44',
// '/style-transfer/models/la_muse/Variable_45',
// '/style-transfer/models/la_muse/Variable_46',
// '/style-transfer/models/la_muse/Variable_47',
// '/style-transfer/models/la_muse/Variable_5',
// '/style-transfer/models/la_muse/Variable_6',
// '/style-transfer/models/la_muse/Variable_7',
// '/style-transfer/models/la_muse/Variable_8',
// '/style-transfer/models/la_muse/Variable_9',
// '/style-transfer/models/mathura/manifest.json',
// '/style-transfer/models/mathura/Variable',
// '/style-transfer/models/mathura/Variable_1',
// '/style-transfer/models/mathura/Variable_10',
// '/style-transfer/models/mathura/Variable_11',
// '/style-transfer/models/mathura/Variable_12',
// '/style-transfer/models/mathura/Variable_13',
// '/style-transfer/models/mathura/Variable_14',
// '/style-transfer/models/mathura/Variable_15',
// '/style-transfer/models/mathura/Variable_16',
// '/style-transfer/models/mathura/Variable_17',
// '/style-transfer/models/mathura/Variable_18',
// '/style-transfer/models/mathura/Variable_19',
// '/style-transfer/models/mathura/Variable_2',
// '/style-transfer/models/mathura/Variable_20',
// '/style-transfer/models/mathura/Variable_21',
// '/style-transfer/models/mathura/Variable_22',
// '/style-transfer/models/mathura/Variable_23',
// '/style-transfer/models/mathura/Variable_24',
// '/style-transfer/models/mathura/Variable_25',
// '/style-transfer/models/mathura/Variable_26',
// '/style-transfer/models/mathura/Variable_27',
// '/style-transfer/models/mathura/Variable_28',
// '/style-transfer/models/mathura/Variable_29',
// '/style-transfer/models/mathura/Variable_3',
// '/style-transfer/models/mathura/Variable_30',
// '/style-transfer/models/mathura/Variable_31',
// '/style-transfer/models/mathura/Variable_32',
// '/style-transfer/models/mathura/Variable_33',
// '/style-transfer/models/mathura/Variable_34',
// '/style-transfer/models/mathura/Variable_35',
// '/style-transfer/models/mathura/Variable_36',
// '/style-transfer/models/mathura/Variable_37',
// '/style-transfer/models/mathura/Variable_38',
// '/style-transfer/models/mathura/Variable_39',
// '/style-transfer/models/mathura/Variable_4',
// '/style-transfer/models/mathura/Variable_40',
// '/style-transfer/models/mathura/Variable_41',
// '/style-transfer/models/mathura/Variable_42',
// '/style-transfer/models/mathura/Variable_43',
// '/style-transfer/models/mathura/Variable_44',
// '/style-transfer/models/mathura/Variable_45',
// '/style-transfer/models/mathura/Variable_46',
// '/style-transfer/models/mathura/Variable_47',
// '/style-transfer/models/mathura/Variable_5',
// '/style-transfer/models/mathura/Variable_6',
// '/style-transfer/models/mathura/Variable_7',
// '/style-transfer/models/mathura/Variable_8',
// '/style-transfer/models/mathura/Variable_9',
// '/style-transfer/models/matilde_perez/manifest.json',
// '/style-transfer/models/matilde_perez/Variable',
// '/style-transfer/models/matilde_perez/Variable_1',
// '/style-transfer/models/matilde_perez/Variable_10',
// '/style-transfer/models/matilde_perez/Variable_11',
// '/style-transfer/models/matilde_perez/Variable_12',
// '/style-transfer/models/matilde_perez/Variable_13',
// '/style-transfer/models/matilde_perez/Variable_14',
// '/style-transfer/models/matilde_perez/Variable_15',
// '/style-transfer/models/matilde_perez/Variable_16',
// '/style-transfer/models/matilde_perez/Variable_17',
// '/style-transfer/models/matilde_perez/Variable_18',
// '/style-transfer/models/matilde_perez/Variable_19',
// //'style-transfer/models/matilde_perez/Variable_2',
// '/style-transfer/models/matilde_perez/Variable_20',
// '/style-transfer/models/matilde_perez/Variable_21',
// '/style-transfer/models/matilde_perez/Variable_22',
// '/style-transfer/models/matilde_perez/Variable_23',
// '/style-transfer/models/matilde_perez/Variable_24',
// '/style-transfer/models/matilde_perez/Variable_25',
// '/style-transfer/models/matilde_perez/Variable_26',
// '/style-transfer/models/matilde_perez/Variable_27',
// '/style-transfer/models/matilde_perez/Variable_28',
// '/style-transfer/models/matilde_perez/Variable_29',
// '/style-transfer/models/matilde_perez/Variable_3',
// '/style-transfer/models/matilde_perez/Variable_30',
// '/style-transfer/models/matilde_perez/Variable_31',
// '/style-transfer/models/matilde_perez/Variable_32',
// '/style-transfer/models/matilde_perez/Variable_33',
// '/style-transfer/models/matilde_perez/Variable_34',
// '/style-transfer/models/matilde_perez/Variable_35',
// '/style-transfer/models/matilde_perez/Variable_36',
// '/style-transfer/models/matilde_perez/Variable_37',
// '/style-transfer/models/matilde_perez/Variable_38',
// '/style-transfer/models/matilde_perez/Variable_39',
// '/style-transfer/models/matilde_perez/Variable_4',
// '/style-transfer/models/matilde_perez/Variable_40',
// '/style-transfer/models/matilde_perez/Variable_41',
// '/style-transfer/models/matilde_perez/Variable_42',
// '/style-transfer/models/matilde_perez/Variable_43',
// '/style-transfer/models/matilde_perez/Variable_44',
// '/style-transfer/models/matilde_perez/Variable_45',
// '/style-transfer/models/matilde_perez/Variable_46',
// '/style-transfer/models/matilde_perez/Variable_47',
// '/style-transfer/models/matilde_perez/Variable_5',
// '/style-transfer/models/matilde_perez/Variable_6',
// '/style-transfer/models/matilde_perez/Variable_7',
// '/style-transfer/models/matilde_perez/Variable_8',
// '/style-transfer/models/matilde_perez/Variable_9',
// '/style-transfer/models/rain_princess/manifest.json',
// '/style-transfer/models/rain_princess/Variable',
// '/style-transfer/models/rain_princess/Variable_1',
// '/style-transfer/models/rain_princess/Variable_10',
// '/style-transfer/models/rain_princess/Variable_11',
// '/style-transfer/models/rain_princess/Variable_12',
// '/style-transfer/models/rain_princess/Variable_13',
// '/style-transfer/models/rain_princess/Variable_14',
// '/style-transfer/models/rain_princess/Variable_15',
// '/style-transfer/models/rain_princess/Variable_16',
// '/style-transfer/models/rain_princess/Variable_17',
// '/style-transfer/models/rain_princess/Variable_18',
// '/style-transfer/models/rain_princess/Variable_19',
// '/style-transfer/models/rain_princess/Variable_2',
// '/style-transfer/models/rain_princess/Variable_20',
// '/style-transfer/models/rain_princess/Variable_21',
// '/style-transfer/models/rain_princess/Variable_22',
// '/style-transfer/models/rain_princess/Variable_23',
// '/style-transfer/models/rain_princess/Variable_24',
// '/style-transfer/models/rain_princess/Variable_25',
// '/style-transfer/models/rain_princess/Variable_26',
// '/style-transfer/models/rain_princess/Variable_27',
// '/style-transfer/models/rain_princess/Variable_28',
// '/style-transfer/models/rain_princess/Variable_29',
// '/style-transfer/models/rain_princess/Variable_3',
// '/style-transfer/models/rain_princess/Variable_30',
// '/style-transfer/models/rain_princess/Variable_31',
// '/style-transfer/models/rain_princess/Variable_32',
// '/style-transfer/models/rain_princess/Variable_33',
// '/style-transfer/models/rain_princess/Variable_34',
// '/style-transfer/models/rain_princess/Variable_35',
// '/style-transfer/models/rain_princess/Variable_36',
// '/style-transfer/models/rain_princess/Variable_37',
// '/style-transfer/models/rain_princess/Variable_38',
// '/style-transfer/models/rain_princess/Variable_39',
// '/style-transfer/models/rain_princess/Variable_4',
// '/style-transfer/models/rain_princess/Variable_40',
// '/style-transfer/models/rain_princess/Variable_41',
// '/style-transfer/models/rain_princess/Variable_42',
// '/style-transfer/models/rain_princess/Variable_43',
// '/style-transfer/models/rain_princess/Variable_44',
// '/style-transfer/models/rain_princess/Variable_45',
// '/style-transfer/models/rain_princess/Variable_46',
// '/style-transfer/models/rain_princess/Variable_47',
// '/style-transfer/models/rain_princess/Variable_5',
// '/style-transfer/models/rain_princess/Variable_6',
// '/style-transfer/models/rain_princess/Variable_7',
// '/style-transfer/models/rain_princess/Variable_8',
// '/style-transfer/models/rain_princess/Variable_9',
// '/style-transfer/models/matta/manifest.json',
// '/style-transfer/models/matta/Variable',
// '/style-transfer/models/matta/Variable_1',
// '/style-transfer/models/matta/Variable_10',
// '/style-transfer/models/matta/Variable_11',
// '/style-transfer/models/matta/Variable_12',
// '/style-transfer/models/matta/Variable_13',
// '/style-transfer/models/matta/Variable_14',
// '/style-transfer/models/matta/Variable_15',
// '/style-transfer/models/matta/Variable_16',
// '/style-transfer/models/matta/Variable_17',
// '/style-transfer/models/matta/Variable_18',
// '/style-transfer/models/matta/Variable_19',
// '/style-transfer/models/matta/Variable_2',
// '/style-transfer/models/matta/Variable_20',
// '/style-transfer/models/matta/Variable_21',
// '/style-transfer/models/matta/Variable_22',
// '/style-transfer/models/matta/Variable_23',
// '/style-transfer/models/matta/Variable_24',
// '/style-transfer/models/matta/Variable_25',
// '/style-transfer/models/matta/Variable_26',
// '/style-transfer/models/matta/Variable_27',
// '/style-transfer/models/matta/Variable_28',
// '/style-transfer/models/matta/Variable_29',
// '/style-transfer/models/matta/Variable_3',
// '/style-transfer/models/matta/Variable_30',
// '/style-transfer/models/matta/Variable_31',
// '/style-transfer/models/matta/Variable_32',
// '/style-transfer/models/matta/Variable_33',
// '/style-transfer/models/matta/Variable_34',
// '/style-transfer/models/matta/Variable_35',
// '/style-transfer/models/matta/Variable_36',
// '/style-transfer/models/matta/Variable_37',
// '/style-transfer/models/matta/Variable_38',
// '/style-transfer/models/matta/Variable_39',
// '/style-transfer/models/matta/Variable_4',
// '/style-transfer/models/matta/Variable_40',
// '/style-transfer/models/matta/Variable_41',
// '/style-transfer/models/matta/Variable_42',
// '/style-transfer/models/matta/Variable_43',
// '/style-transfer/models/matta/Variable_44',
// '/style-transfer/models/matta/Variable_45',
// '/style-transfer/models/matta/Variable_46',
// '/style-transfer/models/matta/Variable_47',
// '/style-transfer/models/matta/Variable_5',
// '/style-transfer/models/matta/Variable_6',
// '/style-transfer/models/matta/Variable_7',
// '/style-transfer/models/matta/Variable_8',
// '/style-transfer/models/matta/Variable_9',
// '/style-transfer/models/scream/manifest.json',
// '/style-transfer/models/scream/Variable',
// '/style-transfer/models/scream/Variable_1',
// '/style-transfer/models/scream/Variable_10',
// '/style-transfer/models/scream/Variable_11',
// '/style-transfer/models/scream/Variable_12',
// '/style-transfer/models/scream/Variable_13',
// '/style-transfer/models/scream/Variable_14',
// '/style-transfer/models/scream/Variable_15',
// '/style-transfer/models/scream/Variable_16',
// '/style-transfer/models/scream/Variable_17',
// '/style-transfer/models/scream/Variable_18',
// '/style-transfer/models/scream/Variable_19',
// '/style-transfer/models/scream/Variable_2',
// '/style-transfer/models/scream/Variable_20',
// '/style-transfer/models/scream/Variable_21',
// '/style-transfer/models/scream/Variable_22',
// '/style-transfer/models/scream/Variable_23',
// '/style-transfer/models/scream/Variable_24',
// '/style-transfer/models/scream/Variable_25',
// '/style-transfer/models/scream/Variable_26',
// '/style-transfer/models/scream/Variable_27',
// '/style-transfer/models/scream/Variable_28',
// '/style-transfer/models/scream/Variable_29',
// '/style-transfer/models/scream/Variable_3',
// '/style-transfer/models/scream/Variable_30',
// '/style-transfer/models/scream/Variable_31',
// '/style-transfer/models/scream/Variable_32',
// '/style-transfer/models/scream/Variable_33',
// '/style-transfer/models/scream/Variable_34',
// '/style-transfer/models/scream/Variable_35',
// '/style-transfer/models/scream/Variable_36',
// '/style-transfer/models/scream/Variable_37',
// '/style-transfer/models/scream/Variable_38',
// '/style-transfer/models/scream/Variable_39',
// '/style-transfer/models/scream/Variable_4',
// '/style-transfer/models/scream/Variable_40',
// '/style-transfer/models/scream/Variable_41',
// '/style-transfer/models/scream/Variable_42',
// '/style-transfer/models/scream/Variable_43',
// '/style-transfer/models/scream/Variable_44',
// '/style-transfer/models/scream/Variable_45',
// '/style-transfer/models/scream/Variable_46',
// '/style-transfer/models/scream/Variable_47',
// '/style-transfer/models/scream/Variable_5',
// '/style-transfer/models/scream/Variable_6',
// '/style-transfer/models/scream/Variable_7',
// '/style-transfer/models/scream/Variable_8',
// '/style-transfer/models/scream/Variable_9',
// '/style-transfer/models/udnie/manifest.json',
// '/style-transfer/models/udnie/Variable',
// '/style-transfer/models/udnie/Variable_1',
// '/style-transfer/models/udnie/Variable_10',
// '/style-transfer/models/udnie/Variable_11',
// '/style-transfer/models/udnie/Variable_12',
// '/style-transfer/models/udnie/Variable_13',
// '/style-transfer/models/udnie/Variable_14',
// '/style-transfer/models/udnie/Variable_15',
// '/style-transfer/models/udnie/Variable_16',
// '/style-transfer/models/udnie/Variable_17',
// '/style-transfer/models/udnie/Variable_18',
// '/style-transfer/models/udnie/Variable_19',
// '/style-transfer/models/udnie/Variable_2',
// '/style-transfer/models/udnie/Variable_20',
// '/style-transfer/models/udnie/Variable_21',
// '/style-transfer/models/udnie/Variable_22',
// '/style-transfer/models/udnie/Variable_23',
// '/style-transfer/models/udnie/Variable_24',
// '/style-transfer/models/udnie/Variable_25',
// '/style-transfer/models/udnie/Variable_26',
// '/style-transfer/models/udnie/Variable_27',
// '/style-transfer/models/udnie/Variable_28',
// '/style-transfer/models/udnie/Variable_29',
// '/style-transfer/models/udnie/Variable_3',
// '/style-transfer/models/udnie/Variable_30',
// '/style-transfer/models/udnie/Variable_31',
// '/style-transfer/models/udnie/Variable_32',
// '/style-transfer/models/udnie/Variable_33',
// '/style-transfer/models/udnie/Variable_34',
// '/style-transfer/models/udnie/Variable_35',
// '/style-transfer/models/udnie/Variable_36',
// '/style-transfer/models/udnie/Variable_37',
// '/style-transfer/models/udnie/Variable_38',
// '/style-transfer/models/udnie/Variable_39',
// '/style-transfer/models/udnie/Variable_4',
// '/style-transfer/models/udnie/Variable_40',
// '/style-transfer/models/udnie/Variable_41',
// '/style-transfer/models/udnie/Variable_42',
// '/style-transfer/models/udnie/Variable_43',
// '/style-transfer/models/udnie/Variable_44',
// '/style-transfer/models/udnie/Variable_45',
// '/style-transfer/models/udnie/Variable_46',
// '/style-transfer/models/udnie/Variable_47',
// '/style-transfer/models/udnie/Variable_5',
// '/style-transfer/models/udnie/Variable_6',
// '/style-transfer/models/udnie/Variable_7',
// '/style-transfer/models/udnie/Variable_8',
// '/style-transfer/models/udnie/Variable_9',
// '/style-transfer/models/wave/manifest.json',
// '/style-transfer/models/wave/Variable',
// '/style-transfer/models/wave/Variable_1',
// '/style-transfer/models/wave/Variable_10',
// '/style-transfer/models/wave/Variable_11',
// '/style-transfer/models/wave/Variable_12',
// '/style-transfer/models/wave/Variable_13',
// '/style-transfer/models/wave/Variable_14',
// '/style-transfer/models/wave/Variable_15',
// '/style-transfer/models/wave/Variable_16',
// '/style-transfer/models/wave/Variable_17',
// '/style-transfer/models/wave/Variable_18',
// '/style-transfer/models/wave/Variable_19',
// '/style-transfer/models/wave/Variable_2',
// '/style-transfer/models/wave/Variable_20',
// '/style-transfer/models/wave/Variable_21',
// '/style-transfer/models/wave/Variable_22',
// '/style-transfer/models/wave/Variable_23',
// '/style-transfer/models/wave/Variable_24',
// '/style-transfer/models/wave/Variable_25',
// '/style-transfer/models/wave/Variable_26',
// '/style-transfer/models/wave/Variable_27',
// '/style-transfer/models/wave/Variable_28',
// '/style-transfer/models/wave/Variable_29',
// '/style-transfer/models/wave/Variable_3',
// '/style-transfer/models/wave/Variable_30',
// '/style-transfer/models/wave/Variable_31',
// '/style-transfer/models/wave/Variable_32',
// '/style-transfer/models/wave/Variable_33',
// '/style-transfer/models/wave/Variable_34',
// '/style-transfer/models/wave/Variable_35',
// '/style-transfer/models/wave/Variable_36',
// '/style-transfer/models/wave/Variable_37',
// '/style-transfer/models/wave/Variable_38',
// '/style-transfer/models/wave/Variable_39',
// '/style-transfer/models/wave/Variable_4',
// '/style-transfer/models/wave/Variable_40',
// '/style-transfer/models/wave/Variable_41',
// '/style-transfer/models/wave/Variable_42',
// '/style-transfer/models/wave/Variable_43',
// '/style-transfer/models/wave/Variable_44',
// '/style-transfer/models/wave/Variable_45',
// '/style-transfer/models/wave/Variable_46',
// '/style-transfer/models/wave/Variable_47',
// '/style-transfer/models/wave/Variable_5',
// '/style-transfer/models/wave/Variable_6',
// '/style-transfer/models/wave/Variable_7',
// '/style-transfer/models/wave/Variable_8',
// '/style-transfer/models/wave/Variable_9',
// '/style-transfer/models/wreck/manifest.json',
// '/style-transfer/models/wreck/Variable',
// '/style-transfer/models/wreck/Variable_1',
// '/style-transfer/models/wreck/Variable_10',
// '/style-transfer/models/wreck/Variable_11',
// '/style-transfer/models/wreck/Variable_12',
// '/style-transfer/models/wreck/Variable_13',
// '/style-transfer/models/wreck/Variable_14',
// '/style-transfer/models/wreck/Variable_15',
// '/style-transfer/models/wreck/Variable_16',
// '/style-transfer/models/wreck/Variable_17',
// '/style-transfer/models/wreck/Variable_18',
// '/style-transfer/models/wreck/Variable_19',
// '/style-transfer/models/wreck/Variable_2',
// '/style-transfer/models/wreck/Variable_20',
// '/style-transfer/models/wreck/Variable_21',
// '/style-transfer/models/wreck/Variable_22',
// '/style-transfer/models/wreck/Variable_23',
// '/style-transfer/models/wreck/Variable_24',
// '/style-transfer/models/wreck/Variable_25',
// '/style-transfer/models/wreck/Variable_26',
// '/style-transfer/models/wreck/Variable_27',
// '/style-transfer/models/wreck/Variable_28',
// '/style-transfer/models/wreck/Variable_29',
// '/style-transfer/models/wreck/Variable_3',
// '/style-transfer/models/wreck/Variable_30',
// '/style-transfer/models/wreck/Variable_31',
// '/style-transfer/models/wreck/Variable_32',
// '/style-transfer/models/wreck/Variable_33',
// '/style-transfer/models/wreck/Variable_34',
// '/style-transfer/models/wreck/Variable_35',
// '/style-transfer/models/wreck/Variable_36',
// '/style-transfer/models/wreck/Variable_37',
// '/style-transfer/models/wreck/Variable_38',
// '/style-transfer/models/wreck/Variable_39',
// '/style-transfer/models/wreck/Variable_4',
// '/style-transfer/models/wreck/Variable_40',
// '/style-transfer/models/wreck/Variable_41',
// '/style-transfer/models/wreck/Variable_42',
// '/style-transfer/models/wreck/Variable_43',
// '/style-transfer/models/wreck/Variable_44',
// '/style-transfer/models/wreck/Variable_45',
// '/style-transfer/models/wreck/Variable_46',
// '/style-transfer/models/wreck/Variable_47',
// '/style-transfer/models/wreck/Variable_5',
// '/style-transfer/models/wreck/Variable_6',
// '/style-transfer/models/wreck/Variable_7',
// '/style-transfer/models/wreck/Variable_8',
// '/style-transfer/models/wreck/Variable_9',
// '/tensorflow/AI%20blocks%20QA.json',
// '/tensorflow/AI%20blocks%20QA.weights.bin',
// '/tensorflow/confidences.json',
// '/tensorflow/confidences.weights.bin',
// '/tensorflow/denmark%202010-2016%20flu.txt',
// '/tensorflow/distance%20training%20data.json',
// '/tensorflow/distance.json',
// '/tensorflow/distance.weights.bin',
// '/tensorflow/EI000003969.txt',
// '/tensorflow/guess%20relation%20training%20data.json',
// '/tensorflow/guess%20relation.json',
// '/tensorflow/guess%20relation.weights.bin',
// '/tensorflow/hyperparameters_search.html',
// '/tensorflow/Iceland%20flu%202011-2016.txt',
'tensorflow/index.html',
// '/tensorflow/ireland%202013-2016%20flu.txt',
// '/tensorflow/iweekly%20flu.json',
// '/tensorflow/iweekly%20flu.weights.bin',
// '/tensorflow/layers_help.html',
// '/tensorflow/model%20100-50-20.json',
// '/tensorflow/model%20100-50-20.weights.bin',
// '/tensorflow/model%2050-20-10-5.json',
// '/tensorflow/model%2050-20-10-5.weights.bin',
// '/tensorflow/my-model.json',
// '/tensorflow/my-model.weights.bin',
// '/tensorflow/new%20model%20100-50-20.json',
// '/tensorflow/new%20model%20100-50-20.weights.bin',
// '/tensorflow/new%20model%2050-20-10-5.json',
// '/tensorflow/new%20model%2050-20-10-5.weights.bin',
// '/tensorflow/sample.html',
// '/tensorflow/sample2.html',
// '/tensorflow/sample3.html',
// '/tensorflow/sequence.json',
// '/tensorflow/sequence.weights.bin',
// '/tensorflow/sequential_1.json',
// '/tensorflow/sequential_1.weights.bin',
// '/tensorflow/square%20root%20training%20data.json',
// '/tensorflow/square%20root.json',
// '/tensorflow/square%20root.weights.bin',
// '/tensorflow/Switerland%202011-2016%20flu.txt',
// '/tensorflow/SZ000003700.txt',
'tensorflow/tensorflow.js',
// '/tensorflow/test.js',
// '/tensorflow/tic%20tac%20toe%201.json',
// '/tensorflow/tic%20tac%20toe%201.weights.bin',
// '/tensorflow/training%20data%20-%20model%20100-50-20.json',
// '/tensorflow/training%20data%20-%20model%2050-20-10-5.json',
// '/tensorflow/training%20data%20-%20tic%20tac%20toe%201.json',
// '/tensorflow/training%20data.json',
// '/tensorflow/Training%20with%2080%%20Swiss%20and%20Irish.json',
// '/tensorflow/Training%20with%2080%%20Swiss%20and%20Irish.weights.bin',
// '/tensorflow/Training%20with%20all%20Swiss.json',
// '/tensorflow/Training%20with%20all%20Swiss.weights.bin',
'tensorflow/training_help.html',
// '/tensorflow/validation%20data.json',
// '/tensorflow/weekly%20flu.json',
// '/tensorflow/weekly%20flu.weights.bin',
'tic-tac-toe/index.html',
'tic-tac-toe/tic-tac-toe.js',
'word-embeddings/de/wiki-words.js',
'word-embeddings/de/word-locations.js',
// '/word-embeddings/el/wiki-words.js',
// '/word-embeddings/el/word-locations.js',
'word-embeddings/en/wiki-words.js',
'word-embeddings/en/word-locations.js',
// '/word-embeddings/es/wiki-words.js',
// '/word-embeddings/es/word-locations.js',
// '/word-embeddings/fi/wiki-words.js',
// '/word-embeddings/fi/word-locations.js',
// '/word-embeddings/fr/wiki-words.js',
// '/word-embeddings/fr/word-locations.js',
// '/word-embeddings/hi/wiki-words.js',
// '/word-embeddings/hi/word-locations.js',
// '/word-embeddings/it/wiki-words.js',
// '/word-embeddings/it/word-locations.js',
'word-embeddings/id/wiki-words.js',
'word-embeddings/id/word-locations.js',
// '/word-embeddings/ja/wiki-words.js',
// '/word-embeddings/ja/word-locations.js',
// '/word-embeddings/lt/wiki-words.js',
// '/word-embeddings/lt/word-locations.js',
// '/word-embeddings/pt/wiki-words.js',
// '/word-embeddings/pt/word-locations.js',
// '/word-embeddings/si/wiki-words.js',
// '/word-embeddings/si/word-locations.js',
// '/word-embeddings/sv/wiki-words.js',
// '/word-embeddings/sv/word-locations.js',
// '/word-embeddings/zh/wiki-words.js',
// '/word-embeddings/zh/word-locations.js',

    ];

/* Start the service worker and cache all of the app's content */
self.addEventListener('install', function(e) {
    e.waitUntil(
        caches.open(cacheName).then(function(cache) {
            return cache.addAll(filesToCache); //.slice(0, 1100));
        })
    );
});

self.addEventListener('activate', (evt) => {
    evt.waitUntil(
        caches.keys().then((keyList) => {
            return Promise.all(keyList.map((key) => {
                if (key !== cacheName) {
                    return caches.delete(key);
                }
            }));
        })
    );
    self.clients.claim();
});

/* Serve cached content when offline */
self.addEventListener('fetch', function(e) {
    e.respondWith(
        caches.match(e.request).then(function(response) {
            return response || fetch(e.request);
        })
    );
});


