add_to_dataset({
    "normal": [

],
"non-serious": [
    "images/danderm non-serious/Brittle nails (1).jpg",
    "images/danderm non-serious/Brittle nails (3).jpg",
    "images/danderm non-serious/Brittle nails (4).jpg",
    "images/danderm non-serious/Brittle nails (5).jpg",
    "images/danderm non-serious/Brittle nails.jpg",
    "images/danderm non-serious/Onychomycosis (4).jpg",
    "images/danderm non-serious/Onychomycosis (5).jpg",
    "images/danderm non-serious/Onychomycosis (7).jpg",
    "images/danderm non-serious/Onychomycosis.jpg",
// note the following are listed as serious but after consulting with Anne belongs in abnormal but not serious
"images/danderm serious/Onycholysis (1).jpg",
"images/danderm serious/Onycholysis.jpg",
"images/danderm serious/Onycholysis traumatic 1 of 2.jpg",
"images/danderm serious/Onycholysis (traumatic).jpg",
"images/danderm serious/Onycholysis, traumatic occupational in a slaughterhouse worker from removing hog hides.jpg",
    
],
"warrants second opinion": [
"images/danderm serious/20 nail dystrophy (1 of 4).jpg",
"images/danderm serious/20 nail dystrophy (2 of 4).jpg",
"images/danderm serious/20 nail dystrophy (3 of 4).jpg",
"images/danderm serious/20 nail dystrophy (4 of 4).jpg",
"images/danderm serious/4-73-1 Psoriasis - early proximal lesions.jpg",
"images/danderm serious/A Beau groove (1).jpg",
"images/danderm serious/A Beau groove (2).jpg",
"images/danderm serious/A Beau groove (3).jpg",
"images/danderm serious/A Beau groove (4).jpg",
"images/danderm serious/A Beau groove (5).jpg",
"images/danderm serious/A Beau groove.jpg",
"images/danderm serious/Acute paronychion (1).jpg",
"images/danderm serious/Acute paronychion (2).jpg",
"images/danderm serious/Acute paronychion.jpg",
"images/danderm serious/Chronic paronychion (1 of 2).jpg",
"images/danderm serious/Chronic paronychion (2 of 2).jpg",
"images/danderm serious/Chronic paronychion.jpg",
"images/danderm serious/Clubbing of fingers 1 of 2.jpg",
"images/danderm serious/Clubbing of the nails.jpg",
"images/danderm serious/Dariers disease of the nails (1).jpg",
"images/danderm serious/Dariers disease of the nails.jpg",
"images/danderm serious/Depression of the nail due to a myxoid cyst.jpg",
"images/danderm serious/Dystrophia mediana canaliformis.jpg",
"images/danderm serious/Dystrophy of the nail due to subungual exostosis.jpg",
"images/danderm serious/Factitial paronychion.jpg",
"images/danderm serious/Koilonychia (2).jpg",
"images/danderm serious/Koilonychia.jpg",
"images/danderm serious/Leukonychia (4).jpg",
"images/danderm serious/Leukonychia.jpg",
"images/danderm serious/Lichen planus of the nails (1).jpg",
"images/danderm serious/Lichen planus of the nails.jpg",
"images/danderm serious/Lupus erythematosus disseminatus of the paronychion.jpg",
"images/danderm serious/Malalignment of toes (1).jpg",
"images/danderm serious/Nail dystrophy seen in an alcoholic.jpg",
"images/danderm serious/Nail infection with Aspergillus.jpg",
"images/danderm serious/Nail infection with Pseudomonas aeruginosa (7).jpg",
"images/danderm serious/Nail infection with Pseudomonas aeruginosa.jpg",
"images/danderm serious/Onychodystrophy following trauma 20 years previously (note scar on finger).jpg",
"images/danderm serious/Onychophagia (1 of 2).jpg",
"images/danderm serious/Onychophagia (2 of 2).jpg",
"images/danderm serious/Onychotillomania (1).jpg",
"images/danderm serious/Onychotillomania (3).jpg",
"images/danderm serious/Onychotillomania.jpg",
"images/danderm serious/Onychotillomania. Note absence of nail cuticle.jpg",
"images/danderm serious/Periungual abscess.jpg",
"images/danderm serious/Pincer nails (1).jpg",
"images/danderm serious/Pincer nails.jpg",
"images/danderm serious/Psoriasis – nail changes and arthropathy.jpg",
"images/danderm serious/Psoriasis of the nails – onycholysis and subungual lesions.jpg",
"images/danderm serious/Psoriasis of the nails – pitting.jpg",
"images/danderm serious/Psoriasis – severe destructive nail changes in an alcoholic (2 of 2).jpg",
"images/danderm serious/Subungual haemorrhage (traumatic).jpg",
"images/danderm serious/Superficial white onychomycosis (1).jpg",
"images/danderm serious/Superficial white onychomycosis.jpg",
"images/danderm serious/Traumatic nail changes following sports (4).jpg",
"images/danderm serious/Yellow discolorationdue to dihydroxy acetone 3 of 3.jpg",
"images/danderm serious/Yellow nails (1).jpg",
"images/danderm serious/Yellow nails (1 of 2).jpg",
"images/danderm serious/Yellow nails (2 of 2).jpg",
"images/danderm serious/Yellow nails (3).jpg",
"images/danderm serious/Yellow nails.jpg",
]})