add_to_dataset({
    "normal": [

],
"non-serious": [
    "images/dermnet/misc not-serious/Fungal nail infection (1b).png",
    "images/dermnet/misc not-serious/Fungal nail infection (1c).png",
    "images/dermnet/misc not-serious/Fungal nail infection (1).png",
    "images/dermnet/misc not-serious/Fungal nail infection (2).png",
    "images/dermnet/misc not-serious/Fungal nail infection (3).png",
    "images/dermnet/misc not-serious/Fungal nail infection.png", 
    "images/dermnet/onycholysis/onycholysis-0.png",
    "images/dermnet/onycholysis/onycholysis-2.png",
    "images/dermnet/onycholysis/onycholysis-3.png",
    "images/dermnet/onycholysis/onycholysis-4.png",
    "images/dermnet/onycholysis/onycholysis-5.png",
    "images/dermnet/onycholysis/onycholysis-6.png",
    "images/dermnet/onycholysis/onycholysis-8.png",
    "images/dermnet/onycholysis/onychomycosis-1b.png",
    "images/dermnet/onycholysis/onychomycosis-1c.png",
    "images/dermnet/onycholysis/onychomycosis-5b.png",
    "images/dermnet/onycholysis/onychomycosis-6b.png",
    "images/dermnet/onycholysis/onychomycosis-6c.png",
    "images/dermnet/onycholysis/psoriasis-0.png",
    "images/dermnet/onychomycosis/onychomycosis-1.png",
    "images/dermnet/onychomycosis/onychomycosis-2.png",
    "images/dermnet/onychomycosis/onychomycosis-3.png",
    "images/dermnet/onychomycosis/onychomycosis-4.png",
    "images/dermnet/onychomycosis/onychomycosis-5.png",
    "images/dermnet/onychomycosis/onychomycosis-6.png",
    "images/dermnet/psoriasis/psoriasis-0b.png",
    "images/dermnet/psoriasis/psoriasis-10.png",
    "images/dermnet/psoriasis/psoriasis-11.png",
    "images/dermnet/psoriasis/psoriasis-12.png",
    "images/dermnet/psoriasis/psoriasis-13b.png",
    "images/dermnet/psoriasis/psoriasis-13.png",
    "images/dermnet/psoriasis/psoriasis-14b.png",
    "images/dermnet/psoriasis/psoriasis-14.png",
    "images/dermnet/psoriasis/psoriasis-15.png",
    "images/dermnet/psoriasis/psoriasis-16.png",
    "images/dermnet/psoriasis/psoriasis-17.png",
    "images/dermnet/psoriasis/psoriasis-18.png",
    "images/dermnet/psoriasis/psoriasis-19b.png",
    "images/dermnet/psoriasis/psoriasis-19c.png",
    "images/dermnet/psoriasis/psoriasis-19d.png",
    "images/dermnet/psoriasis/psoriasis-19.png",
    "images/dermnet/psoriasis/psoriasis-1b.png",
    "images/dermnet/psoriasis/psoriasis-1.png",
    "images/dermnet/psoriasis/psoriasis-20b.png",
    "images/dermnet/psoriasis/psoriasis-20c.png",
    "images/dermnet/psoriasis/psoriasis-20d.png",
    "images/dermnet/psoriasis/psoriasis-20.png",
    "images/dermnet/psoriasis/psoriasis-21b.png",
    "images/dermnet/psoriasis/psoriasis-21c.png",
    "images/dermnet/psoriasis/psoriasis-21.png",
    "images/dermnet/psoriasis/psoriasis-22b.png",
    "images/dermnet/psoriasis/psoriasis-22c.png",
    "images/dermnet/psoriasis/psoriasis-22.png",
    "images/dermnet/psoriasis/psoriasis-23b.png",
    "images/dermnet/psoriasis/psoriasis-23.png",
    "images/dermnet/psoriasis/psoriasis-24b.png",
    "images/dermnet/psoriasis/psoriasis-24c.png",
    "images/dermnet/psoriasis/psoriasis-24.png",
    "images/dermnet/psoriasis/psoriasis-25b.png",
    "images/dermnet/psoriasis/psoriasis-25c.png",
    "images/dermnet/psoriasis/psoriasis-25d.png",
    "images/dermnet/psoriasis/psoriasis-25.png",
    "images/dermnet/psoriasis/psoriasis-2.png",
    "images/dermnet/psoriasis/psoriasis-30b.png",
    "images/dermnet/psoriasis/psoriasis-30.png",
    "images/dermnet/psoriasis/psoriasis-32.png",
    "images/dermnet/psoriasis/psoriasis-33b.png",
    "images/dermnet/psoriasis/psoriasis-33.png",
    "images/dermnet/psoriasis/psoriasis-34.png",
    "images/dermnet/psoriasis/psoriasis-35.png",
    "images/dermnet/psoriasis/psoriasis-36.png",
    "images/dermnet/psoriasis/psoriasis-37.png",
    "images/dermnet/psoriasis/psoriasis-38.png",
    "images/dermnet/psoriasis/psoriasis-3.png",
    "images/dermnet/psoriasis/psoriasis-41b.png",
    "images/dermnet/psoriasis/psoriasis-41.png",
    "images/dermnet/psoriasis/psoriasis-42b.png",
    "images/dermnet/psoriasis/psoriasis-42c.png",
    "images/dermnet/psoriasis/psoriasis-42.png",
    "images/dermnet/psoriasis/psoriasis-43.png",
    "images/dermnet/psoriasis/psoriasis-44.png",
    "images/dermnet/psoriasis/psoriasis-45.png",
    "images/dermnet/psoriasis/psoriasis-46.png",
    "images/dermnet/psoriasis/psoriasis-47b.png",
    "images/dermnet/psoriasis/psoriasis-47.png",
    "images/dermnet/psoriasis/psoriasis-48b.png",
    "images/dermnet/psoriasis/psoriasis-48.png",
    "images/dermnet/psoriasis/psoriasis-49.png",
    "images/dermnet/psoriasis/psoriasis-4b.png",
    "images/dermnet/psoriasis/psoriasis-4.png",
    "images/dermnet/psoriasis/psoriasis-50b.png",
    "images/dermnet/psoriasis/psoriasis-50c.png",
    "images/dermnet/psoriasis/psoriasis-50.png",
    "images/dermnet/psoriasis/psoriasis-51b.png",
    "images/dermnet/psoriasis/psoriasis-51c.png",
    "images/dermnet/psoriasis/psoriasis-51.png",
    "images/dermnet/psoriasis/psoriasis-52b.png",
    "images/dermnet/psoriasis/psoriasis-52.png",
    "images/dermnet/psoriasis/psoriasis-53.png",
    "images/dermnet/psoriasis/psoriasis-54.png",
    "images/dermnet/psoriasis/psoriasis-55.png",
    "images/dermnet/psoriasis/psoriasis-56.png",
    "images/dermnet/psoriasis/psoriasis-57.png",
    "images/dermnet/psoriasis/psoriasis-58.png",
    "images/dermnet/psoriasis/psoriasis-59b.png",
    "images/dermnet/psoriasis/psoriasis-59.png",
    "images/dermnet/psoriasis/psoriasis-5b.png",
    "images/dermnet/psoriasis/psoriasis-5.png",
    "images/dermnet/psoriasis/psoriasis-60.png",
    "images/dermnet/psoriasis/psoriasis-61.png",
    "images/dermnet/psoriasis/psoriasis-63b.png",
    "images/dermnet/psoriasis/psoriasis-63c.png",
    "images/dermnet/psoriasis/psoriasis-63.png",
    "images/dermnet/psoriasis/psoriasis-64b.png",
    "images/dermnet/psoriasis/psoriasis-64c.png",
    "images/dermnet/psoriasis/psoriasis-64d.png",
    "images/dermnet/psoriasis/psoriasis-64.png",
    "images/dermnet/psoriasis/psoriasis-65b.png",
    "images/dermnet/psoriasis/psoriasis-65.png",
    "images/dermnet/psoriasis/psoriasis-66.png",
    "images/dermnet/psoriasis/psoriasis-67.png",
    "images/dermnet/psoriasis/psoriasis-68.png",
    "images/dermnet/psoriasis/psoriasis-69b.png",
    "images/dermnet/psoriasis/psoriasis-69c.png",
    "images/dermnet/psoriasis/psoriasis-69d.png",
    "images/dermnet/psoriasis/psoriasis-69.png",
    "images/dermnet/psoriasis/psoriasis-6.png",
    "images/dermnet/psoriasis/psoriasis-70.png",
    "images/dermnet/psoriasis/psoriasis-71.png",
    "images/dermnet/psoriasis/psoriasis-72b.png",
    "images/dermnet/psoriasis/psoriasis-72c.png",
    "images/dermnet/psoriasis/psoriasis-72.png",
    "images/dermnet/psoriasis/psoriasis-73.png",
    "images/dermnet/psoriasis/psoriasis-74.png",
    "images/dermnet/psoriasis/psoriasis-75.png",
    "images/dermnet/psoriasis/psoriasis-76b.png",
    "images/dermnet/psoriasis/psoriasis-76c.png",
    "images/dermnet/psoriasis/psoriasis-76d.png",
    "images/dermnet/psoriasis/psoriasis-76.png",
    "images/dermnet/psoriasis/psoriasis-77.png",
    "images/dermnet/psoriasis/psoriasis-78.png",
    "images/dermnet/psoriasis/psoriasis-79b.png",
    "images/dermnet/psoriasis/psoriasis-79c.png",
    "images/dermnet/psoriasis/psoriasis-79.png",
    "images/dermnet/psoriasis/psoriasis-7b.png",
    "images/dermnet/psoriasis/psoriasis-7.png",
    "images/dermnet/psoriasis/psoriasis-80b.png",
    "images/dermnet/psoriasis/psoriasis-80.png",
    "images/dermnet/psoriasis/psoriasis-81b.png",
    "images/dermnet/psoriasis/psoriasis-81.png",
    "images/dermnet/psoriasis/psoriasis-82b.png",
    "images/dermnet/psoriasis/psoriasis-82.png",
    "images/dermnet/psoriasis/psoriasis-83b.png",
    "images/dermnet/psoriasis/psoriasis-83c.png",
    "images/dermnet/psoriasis/psoriasis-83.png",
    "images/dermnet/psoriasis/psoriasis-84b.png",
    "images/dermnet/psoriasis/psoriasis-84c.png",
    "images/dermnet/psoriasis/psoriasis-84.png",
    "images/dermnet/psoriasis/psoriasis-85b.png",
    "images/dermnet/psoriasis/psoriasis-85.png",
    "images/dermnet/psoriasis/psoriasis-86b.png",
    "images/dermnet/psoriasis/psoriasis-86c.png",
    "images/dermnet/psoriasis/psoriasis-86d.png",
    "images/dermnet/psoriasis/psoriasis-86.png",
    "images/dermnet/psoriasis/psoriasis-87.png",
    "images/dermnet/psoriasis/psoriasis-88b.png",
    "images/dermnet/psoriasis/psoriasis-88.png",
    "images/dermnet/psoriasis/psoriasis-89b.png",
    "images/dermnet/psoriasis/psoriasis-89.png",
    "images/dermnet/psoriasis/psoriasis-8b.png",
    "images/dermnet/psoriasis/psoriasis-8c.png",
    "images/dermnet/psoriasis/psoriasis-8d.png",
    "images/dermnet/psoriasis/psoriasis-8e.png",
    "images/dermnet/psoriasis/psoriasis-8f.png",
    "images/dermnet/psoriasis/psoriasis-8g.png",
    "images/dermnet/psoriasis/psoriasis-8h.png",
    "images/dermnet/psoriasis/psoriasis-8.png",
    "images/dermnet/psoriasis/psoriasis-90.png",
    "images/dermnet/psoriasis/psoriasis-91b.png",
    "images/dermnet/psoriasis/psoriasis-91.png",
    "images/dermnet/psoriasis/psoriasis-92b.png",
    "images/dermnet/psoriasis/psoriasis-92c.png",
    "images/dermnet/psoriasis/psoriasis-92.png",
    "images/dermnet/psoriasis/psoriasis-93b.png",
    "images/dermnet/psoriasis/psoriasis-93c.png",
    "images/dermnet/psoriasis/psoriasis-93.png",
    "images/dermnet/psoriasis/psoriasis-94b.png",
    "images/dermnet/psoriasis/psoriasis-94.png",
    "images/dermnet/psoriasis/psoriasis-95b.png",
    "images/dermnet/psoriasis/psoriasis-95.png",
    "images/dermnet/psoriasis/psoriasis-96.png",
    "images/dermnet/psoriasis/psoriasis-97.png",
    "images/dermnet/psoriasis/psoriasis-98.png",
    "images/dermnet/psoriasis/psoriasis-9b.png",
    "images/dermnet/psoriasis/psoriasis-9c.png",
    "images/dermnet/psoriasis/psoriasis-9d.png",
    "images/dermnet/psoriasis/psoriasis-9.png", 
],
"warrants second opinion": [
    "images/dermnet/misc serious/acrocyanosis-wdhb-v2.png",
    "images/dermnet/misc serious/Acrodermatitis continua-b.png",
    "images/dermnet/misc serious/Acrodermatitis-continua-of-Hallopeau-0.png",
    "images/dermnet/misc serious/Acrodermatitis-continua-of-Hallopeau-2-v2-b.png",
    "images/dermnet/misc serious/Acrodermatitis-continua-of-Hallopeau-2-v2-c.png",
    "images/dermnet/misc serious/Acrodermatitis-continua-of-Hallopeau-2-v2-d.png",
    "images/dermnet/misc serious/Acrodermatitis-continua-of-Hallopeau-2-v2.png",
    "images/dermnet/misc serious/Acrodermatitis continua.png",
    "images/dermnet/misc serious/Acute herpetic paronychia.png",
    "images/dermnet/misc serious/Acute paronychia-b.png",
    "images/dermnet/misc serious/Acute paronychia-c.png",
    "images/dermnet/misc serious/Acute paronychia-d.png",
    "images/dermnet/misc serious/Acute paronychia.png",
    "images/dermnet/misc serious/Aging.png",
    "images/dermnet/misc serious/alm13-v2.png",
    "images/dermnet/misc serious/alm-nail-1.png",
    "images/dermnet/misc serious/alm-subungual-0.png",
    "images/dermnet/misc serious/Alopecia areata.png",
    "images/dermnet/misc serious/amelanotic-melanoma-2-v3.png",
    "images/dermnet/misc serious/amelanotic-melanoma-nail-0.png",
    "images/dermnet/misc serious/amelanotic-nail-melanoma-1.png",
    "images/dermnet/misc serious/Angelwing deformity.png",
    "images/dermnet/misc serious/angelwing-lichen-planus-v2.png",
    "images/dermnet/misc serious/Antisynthetase-syndrome-v2-b.png",
    "images/dermnet/misc serious/Antisynthetase-syndrome-v2-c.png",
    "images/dermnet/misc serious/Antisynthetase-syndrome-v2.png",
    "images/dermnet/misc serious/atopicdermatitis-b.png",
    "images/dermnet/misc serious/atopicdermatitis-c.png",
    "images/dermnet/misc serious/atopicdermatitis.png",
    "images/dermnet/misc serious/Beau line.png",
    "images/dermnet/misc serious/beau-lines-0.png",
    "images/dermnet/misc serious/beau-lines-1-v2-b.png",
    "images/dermnet/misc serious/beau-lines-1-v2-c.png",
    "images/dermnet/misc serious/beau-lines-1-v2-d.png",
    "images/dermnet/misc serious/beau-lines-1-v2.png",
    "images/dermnet/misc serious/beau-lines-2-v2.png",
    "images/dermnet/misc serious/Bitten nail.png",
    "images/dermnet/misc serious/bitten.png",
    "images/dermnet/misc serious/Black nails with pseudomonas infection (2).png",
    "images/dermnet/misc serious/Black nails with pseudomonas infection-c.png",
    "images/dermnet/misc serious/Black nails with pseudomonas infection.png",
    "images/dermnet/misc serious/blue-nails-0-b.png",
    "images/dermnet/misc serious/blue-nails-0-c.png",
    "images/dermnet/misc serious/blue-nails-0-d.png",
    "images/dermnet/misc serious/Blue nails due to minocycline-b.png",
    "images/dermnet/misc serious/Blue nails due to minocycline-c.png",
    "images/dermnet/misc serious/Blue nails due to minocycline.png",
    "images/dermnet/misc serious/Candida nail infection.jpg",
    "images/dermnet/misc serious/candida-onychomycosis-0.png",
    "images/dermnet/misc serious/Candida.png",
    "images/dermnet/misc serious/chewed-b.png",
    "images/dermnet/misc serious/chewed-c.png",
    "images/dermnet/misc serious/chewed.png",
    "images/dermnet/misc serious/Chronic paronychia.png",
    "images/dermnet/misc serious/Clubbing-fingers-0-b.png",
    "images/dermnet/misc serious/Clubbing-fingers-0-c.png",
    "images/dermnet/misc serious/Clubbing-fingers-0-d.png",
    "images/dermnet/misc serious/Clubbing-fingers-0.png",
    "images/dermnet/misc serious/clubbing-lung-cancer-2-v2.png",
    "images/dermnet/misc serious/Clubbing-lung-cancer-v2.png",
    "images/dermnet/misc serious/darier-nail-0.png",
    "images/dermnet/misc serious/darier-nail-2-v2.png",
    "images/dermnet/misc serious/darier nail disease.png",
    "images/dermnet/misc serious/Dariers-disease-001-b.png",
    "images/dermnet/misc serious/Dariers-disease-001-c.png",
    "images/dermnet/misc serious/Dariers-disease-001.png",
    "images/dermnet/misc serious/dermatomyositis-nailfold-04-v3-b.png",
    "images/dermnet/misc serious/dermatomyositis-nailfold-04-v3-c.png",
    "images/dermnet/misc serious/dermatomyositis-nailfold-04-v3.png",
    "images/dermnet/misc serious/dermatomyositis-nailfold-06-v3-b.png",
    "images/dermnet/misc serious/dermatomyositis-nailfold-06-v3-c.png",
    "images/dermnet/misc serious/dermatomyositis-nailfold-06-v3.png",
    "images/dermnet/misc serious/Digital-myxoid-cyst-0-v2.png",
    "images/dermnet/misc serious/digital-myxoid-cyst-1-v2.png",
    "images/dermnet/misc serious/digital-myxoid-cyst-2-v2.png",
    "images/dermnet/misc serious/Distal digital infarcts.png",
    "images/dermnet/misc serious/Due to dermatophyte onychomycosis.png",
    "images/dermnet/misc serious/Due to tumour.png",
    "images/dermnet/misc serious/Eczema.png",
    "images/dermnet/misc serious/erythronychia.png",
    "images/dermnet/misc serious/fibroma s.png",
    "images/dermnet/misc serious/fusarium-infection-v2-b.png",
    "images/dermnet/misc serious/fusarium-infection-v2.png",
    "images/dermnet/misc serious/Giant cell tumour of tendon sheath.png",
    "images/dermnet/misc serious/glomus tumor.png",
    "images/dermnet/misc serious/Half and half nail.png",
    "images/dermnet/misc serious/handfootmouthdisease-0-b.png",
    "images/dermnet/misc serious/handfootmouthdisease-0.png",
    "images/dermnet/misc serious/handfootmouthdisese-001-b.png",
    "images/dermnet/misc serious/handfootmouthdisese-001-c.png",
    "images/dermnet/misc serious/handfootmouthdisese-001.png",
    "images/dermnet/misc serious/Hang nail.png",
    "images/dermnet/misc serious/Idiopathic causes-b.png",
    "images/dermnet/misc serious/Idiopathic causes.png",
    "images/dermnet/misc serious/Inclusion epidermal cyst.png",
    "images/dermnet/misc serious/In-growing nail with granuloma formation. Aggravated by retinoids.jpg",
    "images/dermnet/misc serious/Koenen-tumor-in-tuberous-sclerosis-v2.png",
    "images/dermnet/misc serious/lentigo-simplex-nail-0.png",
    "images/dermnet/misc serious/Lichen planus-b.png",
    "images/dermnet/misc serious/Lichen planus-c.png",
    "images/dermnet/misc serious/Lichen planus.png",
    "images/dermnet/misc serious/lichen-planus-wdhb-v2-b.png",
    "images/dermnet/misc serious/lichen-planus-wdhb-v2.png",
    "images/dermnet/misc serious/median-canal-dystrophy-1-b.png",
    "images/dermnet/misc serious/median-canal-dystrophy-1.png",
    "images/dermnet/misc serious/median-canal-dystrophy-2-v2-b.png",
    "images/dermnet/misc serious/median-canal-dystrophy-2-v2.png",
    "images/dermnet/misc serious/median-canaliform-dystrophy-3-v2.png",
    "images/dermnet/misc serious/Median-canaliform-nail-dystrophy-0-b.png",
    "images/dermnet/misc serious/Median-canaliform-nail-dystrophy-0.png",
    "images/dermnet/misc serious/Median canaliform nail dystrophy (2).png",
    "images/dermnet/misc serious/Median canaliform nail dystrophy-b.png",
    "images/dermnet/misc serious/Median canaliform nail dystrophy.png",
    "images/dermnet/misc serious/medianNdystr-b.png",
    "images/dermnet/misc serious/medianNdystr.png",
    "images/dermnet/misc serious/Melanoma.png",
    "images/dermnet/misc serious/melanoma-subungal-0.png",
    "images/dermnet/misc serious/melanoma-subungal-3-v2.png",
    "images/dermnet/misc serious/melanoma-subungal-4-v2.png",
    "images/dermnet/misc serious/Melanonychia (1).png",
    "images/dermnet/misc serious/melanonychia-2-v2.png",
    "images/dermnet/misc serious/Melanonychia-3-v2.png",
    "images/dermnet/misc serious/Melanonychia.png",
    "images/dermnet/misc serious/Melanonychia-race-v2.png",
    "images/dermnet/misc serious/Mixed-connective-tissue-disease-3-v2-b.png",
    "images/dermnet/misc serious/Mixed-connective-tissue-disease-3-v2-c.png",
    "images/dermnet/misc serious/Mixed-connective-tissue-disease-3-v2.png",
    "images/dermnet/misc serious/Muehrcke nail-b.png",
    "images/dermnet/misc serious/Muehrcke nail-c.png",
    "images/dermnet/misc serious/Muehrcke nail.png",
    "images/dermnet/misc serious/Multiple melanonychia-b.png",
    "images/dermnet/misc serious/Multiple melanonychia-c.png",
    "images/dermnet/misc serious/Multiple melanonychia.png",
    "images/dermnet/misc serious/Myxoid cyst (1).png",
    "images/dermnet/misc serious/Myxoid cyst.png",
    "images/dermnet/misc serious/naevus-nail-2.png",
    "images/dermnet/misc serious/naevus-nail-3.png",
    "images/dermnet/misc serious/naevus-nail-6.png",
    "images/dermnet/misc serious/Nail biting-b.png",
    "images/dermnet/misc serious/Nail biting-c.png",
    "images/dermnet/misc serious/Nail biting.png",
    "images/dermnet/misc serious/Nail enlargement due to osteoma-b.png",
    "images/dermnet/misc serious/Nail enlargement due to osteoma.png",
    "images/dermnet/misc serious/nail-fold-capillary-telangiectasia-wdhb-v2.png",
    "images/dermnet/misc serious/Nail fold telangiectasia-b.png",
    "images/dermnet/misc serious/Nail fold telangiectasia-c.png",
    "images/dermnet/misc serious/Nail fold telangiectasia.png",
    "images/dermnet/misc serious/Nail loss due to lichen planus-b.png",
    "images/dermnet/misc serious/Nail loss due to lichen planus.png",
    "images/dermnet/misc serious/Nail melanoma.png",
    "images/dermnet/misc serious/nail patella syndrome.png",
    "images/dermnet/misc serious/nail-patella-syndrome-v2-b.png",
    "images/dermnet/misc serious/nail-patella-syndrome-v2.png",
    "images/dermnet/misc serious/Nail psoriasis-b.png",
    "images/dermnet/misc serious/Nail psoriasis.png",
    "images/dermnet/misc serious/Nail shedding due to lichen planus-b.png",
    "images/dermnet/misc serious/Nail shedding due to lichen planus-c.png",
    "images/dermnet/misc serious/Nail shedding due to lichen planus-d.png",
    "images/dermnet/misc serious/Nail shedding due to lichen planus.png",
    "images/dermnet/misc serious/Nail splitting due to lichen planus.png",
    "images/dermnet/misc serious/Nail splitting_ onychoschizia-b.png",
    "images/dermnet/misc serious/Nail splitting_ onychoschizia.png",
    "images/dermnet/misc serious/onychogryphosis (1).png",
    "images/dermnet/misc serious/Onychogryphosis (2).png",
    "images/dermnet/misc serious/Onychogryphosis-b.png",
    "images/dermnet/misc serious/Onychogryphosis-c.png",
    "images/dermnet/misc serious/Onychogryphosis.png",
    "images/dermnet/misc serious/Onychomatricoma.png",
    "images/dermnet/misc serious/Onychomycosis-0.png",
    "images/dermnet/misc serious/Onychomycosis-2-v2.png",
    "images/dermnet/misc serious/Onychomycosis-b.png",
    "images/dermnet/misc serious/Onychomycosis.png",
    "images/dermnet/misc serious/Oral hydroxyurea.png",
    "images/dermnet/misc serious/paronychia-0-b.png",
    "images/dermnet/misc serious/paronychia-0-c.png",
    "images/dermnet/misc serious/paronychia-0-d.png",
    "images/dermnet/misc serious/paronychia-0.png",
    "images/dermnet/misc serious/paronychia-2-v2-b.png",
    "images/dermnet/misc serious/paronychia-2-v2.png",
    "images/dermnet/misc serious/Paronychia-b.png",
    "images/dermnet/misc serious/Paronychia.png",
    "images/dermnet/misc serious/Periungual fibroma-b.png",
    "images/dermnet/misc serious/Periungual fibroma.png",
    "images/dermnet/misc serious/Periungual warts-b.png",
    "images/dermnet/misc serious/Periungual warts.png",
    "images/dermnet/misc serious/Pincer nail deformity-b.png",
    "images/dermnet/misc serious/Pincer nail deformity.png",
    "images/dermnet/misc serious/Pincer-nail-trumpet-nail-WDHBJPG-v2-b.png",
    "images/dermnet/misc serious/Pincer-nail-trumpet-nail-WDHBJPG-v2.png",
    "images/dermnet/misc serious/Podophyllin.png",
    "images/dermnet/misc serious/Pseudomonas-nail-0.png",
    "images/dermnet/misc serious/pseudomonas-nail-2.png",
    "images/dermnet/misc serious/Psoriasis (1).png",
    "images/dermnet/misc serious/Psoriasis (2b).png",
    "images/dermnet/misc serious/Psoriasis (2c).png",
    "images/dermnet/misc serious/Psoriasis (2).png",
    "images/dermnet/misc serious/Psoriasis (3b).png",
    "images/dermnet/misc serious/Psoriasis (3c).png",
    "images/dermnet/misc serious/Psoriasis (3).png",
    "images/dermnet/misc serious/Psoriasis (4b).png",
    "images/dermnet/misc serious/Psoriasis (4).png",
    "images/dermnet/misc serious/Psoriasis-b.png",
    "images/dermnet/misc serious/Psoriasis-c.png",
    "images/dermnet/misc serious/Psoriasis.png",
    "images/dermnet/misc serious/psoriatic-b.png",
    "images/dermnet/misc serious/psoriatic-nail-032-b.png",
    "images/dermnet/misc serious/psoriatic-nail-032-c.png",
    "images/dermnet/misc serious/psoriatic-nail-032.png",
    "images/dermnet/misc serious/psoriatic-nail-033-b.png",
    "images/dermnet/misc serious/psoriatic-nail-033-c.png",
    "images/dermnet/misc serious/psoriatic-nail-033.png",
    "images/dermnet/misc serious/psoriatic-nail-dystrophy-1-b.png",
    "images/dermnet/misc serious/psoriatic-nail-dystrophy-1.png",
    "images/dermnet/misc serious/Psoriatic nail dystrophy.png",
    "images/dermnet/misc serious/psoriatic-nail-dystrophy-wdhb-1.png",
    "images/dermnet/misc serious/psoriatic-nail-dystrophy-wdhb-2-b.png",
    "images/dermnet/misc serious/psoriatic-nail-dystrophy-wdhb-2-c.png",
    "images/dermnet/misc serious/psoriatic-nail-dystrophy-wdhb-2.png",
    "images/dermnet/misc serious/psoriatic.png",
    "images/dermnet/misc serious/psorkynsi3.png",
    "images/dermnet/misc serious/psorkynsi7.png",
    "images/dermnet/misc serious/psornailclup.png",
    "images/dermnet/misc serious/Pterygium of nail due to lichen planus.png",
    "images/dermnet/misc serious/pyogenic-granuloma-013-v2.png",
    "images/dermnet/misc serious/Ragged cuticles-b.png",
    "images/dermnet/misc serious/Ragged cuticles.png",
    "images/dermnet/misc serious/red longitudinal streak or erythronychia is often due to onychopapilloma.png",
    "images/dermnet/misc serious/Red lunula.png",
    "images/dermnet/misc serious/Resorption of distal phalanx.png",
    "images/dermnet/misc serious/©R Suhonen.png",
    "images/dermnet/misc serious/scabies-089-v2.png",
    "images/dermnet/misc serious/Splinter haemorrhages.png",
    "images/dermnet/misc serious/striate-leukonychia-01-v2.png",
    "images/dermnet/misc serious/subungual-exostosis1-v2.png",
    "images/dermnet/misc serious/Subungual-haematoma-0.png",
    "images/dermnet/misc serious/Subungual-haematoma-2-v2.png",
    "images/dermnet/misc serious/Subungual haematoma.png",
    "images/dermnet/misc serious/Subungual-hyperkeratosis-1.png",
    "images/dermnet/misc serious/Subungual melanoma (2).png",
    "images/dermnet/misc serious/subungual-melanoma-3-600x480-v2.png",
    "images/dermnet/misc serious/Subungual melanoma.png",
    "images/dermnet/misc serious/Subungual squamous cell carcinoma.png",
    "images/dermnet/misc serious/subung-wart-0.png",
    "images/dermnet/misc serious/systemic-lupus-erythematosus-2-v2-b.png",
    "images/dermnet/misc serious/systemic-lupus-erythematosus-2-v2.png",
    "images/dermnet/misc serious/Terry nail (1).png",
    "images/dermnet/misc serious/Terry nail-b.png",
    "images/dermnet/misc serious/Terry nail-c.png",
    "images/dermnet/misc serious/Terry nail-d.png",
    "images/dermnet/misc serious/Terry nail.png",
    "images/dermnet/misc serious/terry-nails-2.png",
    "images/dermnet/misc serious/Tetracycline-b.png",
    "images/dermnet/misc serious/Tetracycline.png",
    "images/dermnet/misc serious/tinea-manuum-004-v2-b.png",
    "images/dermnet/misc serious/tinea-manuum-004-v2.png",
    "images/dermnet/misc serious/tinea-unguium-001.png",
    "images/dermnet/misc serious/tinea-white-superficial-onychomycosis-v2.png",
    "images/dermnet/misc serious/tin-ung1-v2-b.png",
    "images/dermnet/misc serious/tin-ung1-v2.png",
    "images/dermnet/misc serious/trachyonychia-b.jpg",
    "images/dermnet/misc serious/trachyonychia-c.jpg",
    "images/dermnet/misc serious/trachyonychia.jpg",
    "images/dermnet/misc serious/Transverse leukonychia-b.png",
    "images/dermnet/misc serious/Transverse leukonychia-c.png",
    "images/dermnet/misc serious/Transverse leukonychia.png",
    "images/dermnet/misc serious/trauma-nail-0.png",
    "images/dermnet/misc serious/trumpet-nail-0.png",
    "images/dermnet/misc serious/twenty-nail-dystrophy-1-b.png",
    "images/dermnet/misc serious/twenty-nail-dystrophy-1-c.png",
    "images/dermnet/misc serious/twenty-nail-dystrophy-1.png",
    "images/dermnet/misc serious/twenty-nail-dystrophy-2-v2-b.png",
    "images/dermnet/misc serious/twenty-nail-dystrophy-2-v2-c.png",
    "images/dermnet/misc serious/twenty-nail-dystrophy-2-v2.png",
    "images/dermnet/misc serious/Wedge-shaped nails-b.png",
    "images/dermnet/misc serious/Wedge-shaped nails.png",
    "images/dermnet/misc serious/White nail due to vitiligo-b.png",
    "images/dermnet/misc serious/White nail due to vitiligo-c.png",
    "images/dermnet/misc serious/White nail due to vitiligo.png",
    "images/dermnet/misc serious/White spots on nail-b.png",
    "images/dermnet/misc serious/White spots on nail-c.png",
    "images/dermnet/misc serious/White spots on nail.png",
    "images/dermnet/misc serious/White spots on nails.png",
    "images/dermnet/misc serious/yellow-nail3-v2.png",
    "images/dermnet/misc serious/Yellow nails (1).png",
    "images/dermnet/splinter haemorrhage/splinter-0.png",
    "images/dermnet/splinter haemorrhage/splinter-1.png",
    "images/dermnet/splinter haemorrhage/splinter-2.png",
    "images/dermnet/splinter haemorrhage/splinter-3b.png",
    "images/dermnet/splinter haemorrhage/splinter-3.png",
    "images/dermnet/splinter haemorrhage/splinter-4.png",
    "images/dermnet/splinter haemorrhage/splinter-5.png",
    "images/dermnet/splinter haemorrhage/splinter-6.png",
    "images/dermnet/splinter haemorrhage/splinter-8.png",
]})