add_to_dataset({
    "normal": [
"images/hackduke/healthy/Healthy 101.jpg",
"images/hackduke/healthy/Healthy 103.jpg",
"images/hackduke/healthy/Healthy 10.jpg",
"images/hackduke/healthy/Healthy 13.jpg",
"images/hackduke/healthy/Healthy 14.jpg",
"images/hackduke/healthy/Healthy 16.jpg",
"images/hackduke/healthy/Healthy 17.jpg",
"images/hackduke/healthy/Healthy 24.jpg",
"images/hackduke/healthy/Healthy 25.jpg",
"images/hackduke/healthy/Healthy 30.jpg",
"images/hackduke/healthy/Healthy 31.jpg",
"images/hackduke/healthy/Healthy 34.jpg",
"images/hackduke/healthy/Healthy 35.jpg",
"images/hackduke/healthy/Healthy 38.jpg",
"images/hackduke/healthy/Healthy 39.jpg",
"images/hackduke/healthy/Healthy 45.jpg",
"images/hackduke/healthy/Healthy 53.jpg",
"images/hackduke/healthy/Healthy 5.jpg",
"images/hackduke/healthy/Healthy 60.jpg",
"images/hackduke/healthy/Healthy 63.jpg",
"images/hackduke/healthy/Healthy 65.jpg",
"images/hackduke/healthy/Healthy 67.jpg",
"images/hackduke/healthy/Healthy 68.jpg",
"images/hackduke/healthy/Healthy 73.jpg",
"images/hackduke/healthy/Healthy 82.jpg",
"images/hackduke/healthy/Healthy 84.jpg",
"images/hackduke/healthy/Healthy 85.jpg",
"images/hackduke/healthy/Healthy 8.jpg",
"images/hackduke/healthy/Healthy 91.jpg",
"images/hackduke/healthy/Healthy 97.png",
"images/hackduke/healthy/Healthy 9.jpg",
],
"non-serious": [
 // fungal? 
 "images/hackduke/yellow/Yellow 10.png",
"images/hackduke/yellow/Yellow 11.png",
"images/hackduke/yellow/Yellow 12.png",
"images/hackduke/yellow/Yellow 13.png",
"images/hackduke/yellow/Yellow 14.png",
"images/hackduke/yellow/Yellow 15.png",
"images/hackduke/yellow/Yellow 16.png",
"images/hackduke/yellow/Yellow 17.png",
"images/hackduke/yellow/Yellow 18.png",
"images/hackduke/yellow/Yellow 19.png",
"images/hackduke/yellow/Yellow 1.png",
"images/hackduke/yellow/Yellow 20.png",
"images/hackduke/yellow/Yellow 21.png",
"images/hackduke/yellow/Yellow 2.png",
"images/hackduke/yellow/Yellow 3.png",
"images/hackduke/yellow/Yellow 4.png",
"images/hackduke/yellow/Yellow 5.png",
"images/hackduke/yellow/Yellow 6.png",
"images/hackduke/yellow/Yellow 7.png",
"images/hackduke/yellow/Yellow 8.png",
"images/hackduke/yellow/Yellow 9.png",  
],
"warrants second opinion": [
// splinter haemorrhage 
"images/hackduke/darkline/Dark Line 10.png",
"images/hackduke/darkline/Dark Line 14.png",
"images/hackduke/darkline/Dark Line 17.png",
"images/hackduke/darkline/Dark Line22.png",
"images/hackduke/darkline/Dark Line 27.png",
"images/hackduke/darkline/Dark Line 2.png",
"images/hackduke/darkline/Dark Line 31.png",
"images/hackduke/darkline/Dark Line 3.png",
"images/hackduke/darkline/Dark Line 4.png",
"images/hackduke/darkline/Dark Line 7.png",
"images/hackduke/terrys/Terry 10.png",
"images/hackduke/terrys/Terry 11.png",
"images/hackduke/terrys/Terry 12.png",
"images/hackduke/terrys/Terry 13.png",
"images/hackduke/terrys/Terry 14.png",
"images/hackduke/terrys/Terry 15.png",
"images/hackduke/terrys/Terry 16.png",
"images/hackduke/terrys/Terry 17.png",
"images/hackduke/terrys/Terry 18.png",
"images/hackduke/terrys/Terry 19.png",
"images/hackduke/terrys/Terry 1.png",
"images/hackduke/terrys/Terry 20.png",
"images/hackduke/terrys/Terry 21.png",
"images/hackduke/terrys/Terry 22.png",
"images/hackduke/terrys/Terry 23.png",
"images/hackduke/terrys/Terry 24.png",
"images/hackduke/terrys/Terry 25.png",
"images/hackduke/terrys/Terry 26.png",
"images/hackduke/terrys/Terry 27.png",
"images/hackduke/terrys/Terry 28.png",
"images/hackduke/terrys/Terry 29.png",
"images/hackduke/terrys/Terry 2.png",
"images/hackduke/terrys/Terry 30.png",
"images/hackduke/terrys/Terry 31.png",
"images/hackduke/terrys/Terry 32.png",
"images/hackduke/terrys/Terry 33.png",
"images/hackduke/terrys/Terry 34.png",
"images/hackduke/terrys/Terry 35.png",
"images/hackduke/terrys/Terry 36.png",
"images/hackduke/terrys/Terry 37.png",
"images/hackduke/terrys/Terry 3.png",
"images/hackduke/terrys/Terry 4.png",
"images/hackduke/terrys/Terry 5.png",
"images/hackduke/terrys/Terry 6.png",
"images/hackduke/terrys/Terry 7.png",
"images/hackduke/terrys/Terry 8.png",
"images/hackduke/terrys/Terry 9.png",

// "images/hackduke/beaus/Beau10.png",
// "images/hackduke/beaus/Beau1.png",
// "images/hackduke/beaus/Beau3.png",
// "images/hackduke/beaus/Beau4.png",
// "images/hackduke/beaus/Beau5.png",
// "images/hackduke/beaus/Beau6.png",
// "images/hackduke/beaus/Beau7.png",
// "images/hackduke/beaus/Beau8.png",
// "images/hackduke/beaus/Beau9.png",
]})