
add_to_dataset ({
    "normal": [
        {file_name: "images/korean/L_NAIL_5nail_5nail2010_1_normalnail.png",
         count: 345,
         dimensions: {width: 2260,
                      height: 7876}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2014_1_normalnail.png",
         count: 345,
         dimensions: {width: 2260,
                      height: 9156}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2003_1_normalnail.png",
         dimensions: {width: 2260,
                      height: 580}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2003_2_normalnail.png",
         count: 345,
         dimensions: {width: 2260,
                      height: 6596}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2004_1_normalnail.png",
         dimensions: {width: 2260,
                      height: 452}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2004_2_normalnail.png",
         count: 345,
         dimensions: {width: 2260,
                      height: 9284}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2005_2_normalnail.png",
         count: 345,
         dimensions: {width: 2260,
                      height: 9668}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2006_1_normalnail.png",
         dimensions: {width: 2260,
                      height: 324}},

        ],
    "non-serious": [
                   {file_name: "images/korean/L_NAIL_5nailA2_lesion_onychomycosis_onychomycosis.png",
                    count: 250,
                    dimensions: {width: 2260,
                                 height: 6852}},
                   {file_name: "images/korean/L_NAIL_5nailA2_scio_onychomycosis.png",
                    count: 250,
                    dimensions: {width: 2260,
                                 height: 1988}},
                   {file_name: "images/korean/L_NAIL_5nail_5nail2004_2_onychomycosis.png",
//                     count: 139,
                    dimensions: {width: 2260,
                                 height: 1092}},
                   {file_name: "images/korean/L_NAIL_5nail_5nail2006_onychomycosis_onychomycosis.png",
//                     count: 181,
                    dimensions: {width: 2260,
                                 height: 1732}},
                   {file_name: "images/korean/L_NAIL_5nail_5nail2005_2_onychomycosis.png",
//                     count: 180,
                    dimensions: {width: 2260,
                                 height: 1342}},            
                   {file_name: "images/korean/L_NAIL_5nailA2_lesion_onychomycosis_-atypical.png",
                    dimensions: {width: 2260,
                                 height: 708}},   
                   {file_name: "images/korean/L_NAIL_5nailA2_lesion_onychomycosis_-atypical2.png",
                    dimensions: {width: 2260,
                                 height: 324}},
                   {file_name: "images/korean/L_NAIL_5nailA2_lesion_onychomycosis_-focus.png",
                    dimensions: {width: 2260,
                                 height: 964}},
                   {file_name: "images/korean/L_NAIL_5nailA2_lesion_unguium_onychomycosis.png",
                    dimensions: {width: 2260,
                                 height: 1604}},                                
                   {file_name: "images/korean/L_NAIL_5nail_5nail2003_2_onychomycosis.png",
                    dimensions: {width: 2260,
                                 height: 580}},
                                                                    
                                                 ],
    "warrants second opinion": [
        {file_name: "images/korean/L_NAIL_5nailA2_lesion_melanonychia3_melanonychia.png",
//          count: 260,
         dimensions: {width: 2260,
                      height: 1860}},
        {file_name: "images/korean/L_NAIL_5nail_nail2005_2_melanonychia.png",
//          count: 160,
         dimensions: {width: 2260,
                      height: 1220}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2004_2_melanonychia.png",
//          count: 100,
         dimensions: {width: 2260,
                      height: 836}},
        {file_name: "images/korean/L_NAIL_5nailA2_lesion_melanonychia_melanonychia.png",
         dimensions: {width: 2260,
                      height: 324}},
        {file_name: "images/korean/L_NAIL_5nailA2_lesion_melanonychia2_melanonychia.png",
         dimensions: {width: 2260,
                      height: 452}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2003_2_melanonychia.png",
         dimensions: {width: 2260,
                      height: 452}},                                            
        {file_name: "images/korean/L_NAIL_5nail_5nail2007_2_melanonychia.png",
         dimensions: {width: 2260,
                      height: 2372}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2007_2_melanonychia.png",
         dimensions: {width: 2260,
                      height: 2116}}, 
        {file_name: "images/korean/L_NAIL_5nail_5nail2016_melanonychia.png",
         dimensions: {width: 2260,
                      height: 2372}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2014_melanonychia.png",
         dimensions: {width: 2260,
                      height: 1220}},                                     
        {file_name: "images/korean/L_NAIL_5nail_5nail2013_1_melanonychia.png",
         dimensions: {width: 2260,
                      height: 1220}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2005_2_melanonychia.png",
                    dimensions: {width: 2260,
                                 height: 1220}},


                              ],
});

//                 {file_name: "images/korean/L_NAIL_5nailA2_lesion_naildystrophy_onycholysis.png",
//                  count: 161,
//                  dimensions: {width: 2260,
//                               height: 1860}},