add_to_dataset ({
    "normal": [
        {file_name: "images/korean/L_NAIL_5nail_5nail2010_1_normalnail.png",
         count: 250,
         dimensions: {width: 2260,
                      height: 7876}},
        {file_name: "images/korean/L_NAIL_5nail_5nail2014_1_normalnail.png",
         count: 250,
         dimensions: {width: 2260,
                      height: 9156}}
        ],
    "non-serious": [
               {file_name: "images/korean/L_NAIL_5nail_5nail2004_2_onychomycosis.png",
                count: 139,
                dimensions: {width: 2260,
                             height: 1092}},
               {file_name: "images/korean/L_NAIL_5nail_5nail2006_onychomycosis_onychomycosis.png",
                count: 181,
                dimensions: {width: 2260,
                             height: 1732}},
               {file_name: "images/korean/L_NAIL_5nail_5nail2005_2_onychomycosis.png",
                count: 180,
                dimensions: {width: 2260,
                             height: 1342}},    
                ],
    "warrants second opinion": [
        {file_name: "images/korean/L_NAIL_5nailA2_lesion_melanonychia3_melanonychia.png",
         count: 250,
         dimensions: {width: 2260,
                      height: 1860}},
        {file_name: "images/korean/L_NAIL_5nail_nail2005_2_melanonychia.png",
         count: 250,
         dimensions: {width: 2260,
                      height: 1220}},
        ],
});

//                 {file_name: "images/korean/L_NAIL_5nailA2_lesion_naildystrophy_onycholysis.png",
//                  count: 161,
//                  dimensions: {width: 2260,
//                               height: 1860}},